WARN: File "void_return2.php", line 8, characters 3-4:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
WARN: File "void_return2.php", line 8, characters 3-10:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
WARN: File "void_return2.php", line 8, characters 8-10:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
WARN: File "void_return2.php", line 9, characters 10-11:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
ERROR: File "void_return2.php", line 3, characters 10-10:
Was expecting a return type hint (Typing[4030])
ERROR: File "void_return2.php", line 9, characters 3-12:
You cannot return a value (Typing[4084])
  File "void_return2.php", line 7, characters 15-18:
  This is a `void` function
