Code actions available:
------------------------------------------
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 8, "character": 0 },
            "end": { "line": 8, "character": 0 }
          },
          "newText": "    private static async function ${0:method0}(int $x): AsyncKeyedIterator<_, _, _> {\n      foreach (async_it() await as $v) {\n        $x++;\n      }\n    }\n\n"
        },
        {
          "range": {
            "start": { "line": 11, "character": 8 },
            "end": { "line": 13, "character": 9 }
          },
          "newText": "foreach (self::${0:method0}($x) await as $key__ => $value__) {\n            \n        }"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

async function async_it(): AsyncIterator<string> {
  yield "key1";
  yield "key2";
}

class Klass {
    private static async function ${0:method0}(int $x): AsyncKeyedIterator<_, _, _> {
      foreach (async_it() await as $v) {
        $x++;
      }
    }

    public static async function m(int $x): Awaitable<void> {
        $x = 0;
        /*range-start*/
        foreach (self::${0:method0}($x) await as $key__ => $value__) {
            
        }
        /*range-end*/
        $y = $x;
    }
}

<<__EntryPoint>>
function main(): void {
   \HH\Asio\join(Klass::m(1));
}

