Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 5, "character": 0 },
            "end": { "line": 5, "character": 0 }
          },
          "newText": "  private async function ${0:method0}(): Awaitable<void> {\n    $local = await foo();\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 8, "character": 4 },
            "end": { "line": 8, "character": 25 }
          },
          "newText": "await $this->${0:method0}();"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

async function foo(): Awaitable<void> {}

class Klass {
  private async function ${0:method0}(): Awaitable<void> {
    $local = await foo();
  }

  public async function foo(): Awaitable<void> {
    $ignore1 = 1;
    /*range-start*/
    await $this->${0:method0}();
    /*range-end*/
    $ignore2 = 1;
  }
}

