Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 5, "character": 0 },
            "end": { "line": 5, "character": 0 }
          },
          "newText": "  private function ${0:method3}(): void {\n    $x = 1;\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 8, "character": 4 },
            "end": { "line": 8, "character": 11 }
          },
          "newText": "$this->${0:method3}();"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  public function method0(): void {}
  public static async function method1(): Promise<void> {}
  private function ${0:method3}(): void {
    $x = 1;
  }

  public function method2(): void {
    // extracted method should be called "method3" because 0-2 inclusive are taken
    /*range-start*/
    $this->${0:method3}();
    /*range-end*/
  }
}

