Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 7, "character": 0 },
            "end": { "line": 7, "character": 0 }
          },
          "newText": "  private function ${0:method0}(): int {\n    return 3 + 2;\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 10, "character": 28 },
            "end": { "line": 10, "character": 33 }
          },
          "newText": "$this->${0:method0}()"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function cond(): bool {
  return false;
}

class Klass {
  private function ${0:method0}(): int {
    return 3 + 2;
  }

  public function foo(): void {
    if (cond()) {
      while (cond()) {
        $x = /*range-start*/$this->${0:method0}()/*range-end*/;
      }
    }
  }
}

