Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 3, "character": 0 }
          },
          "newText": "  private function ${0:method0}(): vec<int> {\n    $x = vec[1];\n    return $x;\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 4, "character": 19 },
            "end": { "line": 4, "character": 31 }
          },
          "newText": "$x = $this->${0:method0}();"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class A {
  private function ${0:method0}(): vec<int> {
    $x = vec[1];
    return $x;
  }

  public function foo(): void {
    /*range-start*/$x = $this->${0:method0}();/*range-end*/
    var_dump($x);
  }
}

