Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 3, "character": 0 }
          },
          "newText": "  private function ${0:method0}(): KeyedIterator<_> {\n    yield 2 => \"\";\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 5, "character": 4 },
            "end": { "line": 5, "character": 18 }
          },
          "newText": "foreach ($this->${0:method0}() as $key__ => $value__) {\n      \n    }"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  private function ${0:method0}(): KeyedIterator<_> {
    yield 2 => "";
  }

  public function foo(): KeyedIterator<int, string> {
    /*range-start*/
    foreach ($this->${0:method0}() as $key__ => $value__) {
      
    }
    /*range-end*/
  }
}

