Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 3, "character": 0 }
          },
          "newText": "  private function ${0:method0}(): int {\n    return 1 * 2;\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 4, "character": 24 },
            "end": { "line": 4, "character": 29 }
          },
          "newText": "$this->${0:method0}()"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  private function ${0:method0}(): int {
    return 1 * 2;
  }

  public function foo(): void {
    $x = /*range-start*/$this->${0:method0}()/*range-end*/;
  }
}

