Code actions available:
------------------------------------------
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 3, "character": 0 }
          },
          "newText": "  private function ${0:method0}(Awaitable<int> $y): (Awaitable<int>, Awaitable<int>) {\n  $x1 = $y;\n      $x2 = ExtraBuiltins\\genInt()\n      return tuple($x1, $x2);\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 6, "character": 4 },
            "end": { "line": 7, "character": 32 }
          },
          "newText": "list($x1, $x2) = $this->${0:method0}($y);"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  private function ${0:method0}(Awaitable<int> $y): (Awaitable<int>, Awaitable<int>) {
  $x1 = $y;
      $x2 = ExtraBuiltins\genInt()
      return tuple($x1, $x2);
  }

  public async function foo(vec<int> $vec): Awaitable<void> {
    $y = ExtraBuiltins\genInt();
    /*range-start*/
    list($x1, $x2) = $this->${0:method0}($y);
    /*range-end*/
    echo $x1;
    echo await $x2;
  }
}

