Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 5, "character": 0 },
            "end": { "line": 5, "character": 0 }
          },
          "newText": "  private function ${0:method0}(): int {\n    return 3 + 3;\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 9, "character": 21 },
            "end": { "line": 9, "character": 26 }
          },
          "newText": "$this->${0:method0}()"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function foo((function(): int) $f): void {}

class A {
  private function ${0:method0}(): int {
    return 3 + 3;
  }

  public function main(): void {
    foo(() ==>
      // We offer a refactor even though the selection
      // corresponds to a `return` statement in the tast.
      /*range-start*/$this->${0:method0}()/*range-end*/
    );
  }
}

