Code actions available:
------------------------------------------
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 7, "character": 0 },
            "end": { "line": 7, "character": 0 }
          },
          "newText": "  private function ${0:method0}(): void {\n    $x = 1;\n    $y = $x;\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 11, "character": 8 },
            "end": { "line": 12, "character": 16 }
          },
          "newText": "$this->${0:method0}();"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function cond(): bool {
  return false;
}

class Klass {
  private function ${0:method0}(): void {
    $x = 1;
    $y = $x;
  }

  public function foo(): void {
    if (cond()) {
      while (cond()) {
        /*range-start*/
        $this->${0:method0}();
        /*range-end*/;
      }
    }
  }
}

