Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 4, "character": 0 },
            "end": { "line": 4, "character": 0 }
          },
          "newText": "  private function ${0:method0}((bool | string) $z): (bool | string) {\n    $x = $z;\n    return $x;\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 11, "character": 4 },
            "end": { "line": 11, "character": 12 }
          },
          "newText": "$x = $this->${0:method0}($z);"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh


class Klass {
  private function ${0:method0}((bool | string) $z): (bool | string) {
    $x = $z;
    return $x;
  }

  public function foo(): void {
    if (rand()) {
      $z = true;
    } else {
      $z = "";
    }
    /*range-start*/
    $x = $this->${0:method0}($z);/*range-end*/
    $x + 2;
  }
}

