Code actions available:
------------------------------------------
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 3, "character": 0 }
          },
          "newText": "  private function ${0:method0}(\n    int $param1,\n    int $param2,\n    int $param3_and_ret1,\n  ): (int, int) {\n    $param3_and_ret1 = $param3_and_ret1 + $param1;\n    $local = $param3_and_ret1 + $param2;\n    $param3_and_ret1 = $local;\n    $ret2 = 1;\n    return tuple($param3_and_ret1, $ret2);\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 9, "character": 4 },
            "end": { "line": 12, "character": 14 }
          },
          "newText": "list($param3_and_ret1, $ret2) = $this->${0:method0}($param1, $param2, $param3_and_ret1);"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  private function ${0:method0}(
    int $param1,
    int $param2,
    int $param3_and_ret1,
  ): (int, int) {
    $param3_and_ret1 = $param3_and_ret1 + $param1;
    $local = $param3_and_ret1 + $param2;
    $param3_and_ret1 = $local;
    $ret2 = 1;
    return tuple($param3_and_ret1, $ret2);
  }

  public function foo(): void {
    $ignore1 = 1;
    $param1 = 1;
    $param2 = 1;
    $param3_and_ret1 = 1;
    /*range-start*/
    list($param3_and_ret1, $ret2) = $this->${0:method0}($param1, $param2, $param3_and_ret1);
    /*range-end*/
    $ignore2 = 0;
    $ignore3 = $param3_and_ret1;
    $ignore3 = $ret2;
  }
}

