Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 3, "character": 0 }
          },
          "newText": "  private function ${0:method0}(): void {\n    $x = 1;\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 6, "character": 22 },
            "end": { "line": 6, "character": 29 }
          },
          "newText": "$this->${0:method0}();"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  private function ${0:method0}(): void {
    $x = 1;
  }

  public function foo(): void {
    if (1 < 2) {
      // extracting a method here should not change what is printed
      /*range-start*/ $this->${0:method0}(); /*range-end*/
    } else {
      $x = 4;
    }
    echo $x;
  }
}

