Code actions available:
------------------------------------------
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 3, "character": 0 }
          },
          "newText": "  private async function ${0:method0}(int $x): AsyncIterator<_, _, _> {\n    await gen_void();\n    $y = $x;\n    yield 3;\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 5, "character": 4 },
            "end": { "line": 7, "character": 12 }
          },
          "newText": "foreach ($this->${0:method0}($x) await as $value__) {\n      /* TODO: assign to $y */\n      \n    }"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  private async function ${0:method0}(int $x): AsyncIterator<_, _, _> {
    await gen_void();
    $y = $x;
    yield 3;
  }

  public async function foo(int $x): AsyncIterator<int> {
    /*range-start*/
    foreach ($this->${0:method0}($x) await as $value__) {
      /* TODO: assign to $y */
      
    }
    /*range-end*/
    $z = $y
  }
}

