Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 3, "character": 0 }
          },
          "newText": "  private function ${0:method0}(nothing $z): nothing {\n    $x = $z->meth($z);\n    return $x;\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 6, "character": 4 },
            "end": { "line": 6, "character": 22 }
          },
          "newText": "$x = $this->${0:method0}($z);"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  private function ${0:method0}(nothing $z): nothing {
    $x = $z->meth($z);
    return $x;
  }

  public function foo(): void {
    $z = nonexistent();
    /*range-start*/
    $x = $this->${0:method0}($z);/*range-end*/
    $x + 2;
  }
}

