Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 6, "character": 0 },
            "end": { "line": 6, "character": 0 }
          },
          "newText": "  private function ${0:method0}(): int {\n    $return = $this->one();\n    return $return;\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 9, "character": 4 },
            "end": { "line": 9, "character": 27 }
          },
          "newText": "$return = $this->${0:method0}();"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  public function one(): int {
    return 1;
  }
  private function ${0:method0}(): int {
    $return = $this->one();
    return $return;
  }

  public function foo(): void {
    // The extracted function is static iff the function we are extracting from is static.
    /*range-start*/
    $return = $this->${0:method0}();
    /*range-end*/
    var_dump($return);
  }
}

