Code actions available:
------------------------------------------
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 7, "character": 0 },
            "end": { "line": 7, "character": 0 }
          },
          "newText": "  private function ${0:method0}(): (int, Foo<int>) {\n    $return1 = 100;\n    $local = 500 + $return1;\n    $return2 = new Foo($local);\n    return tuple($return1, $return2);\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 10, "character": 4 },
            "end": { "line": 12, "character": 31 }
          },
          "newText": "list($return1, $return2) = $this->${0:method0}();"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class Foo<T> {
  public function __construct(public T $x) {}
}

class Klass {
  private function ${0:method0}(): (int, Foo<int>) {
    $return1 = 100;
    $local = 500 + $return1;
    $return2 = new Foo($local);
    return tuple($return1, $return2);
  }

  public function foo(): void {
    $ignore1 = 1;
    /*range-start*/
    list($return1, $return2) = $this->${0:method0}();
    /*range-end*/
    $ignore2 = 1 + $return1;
    var_dump($return2);
  }
}

