Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 3, "character": 0 }
          },
          "newText": "  private function ${0:method0}(bool $referenced): void {\n    (\n      () ==> {\n        $shadowed = false || $referenced;\n      }\n    );\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 7, "character": 4 },
            "end": { "line": 9, "character": 7 }
          },
          "newText": "$this->${0:method0}($referenced);"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  private function ${0:method0}(bool $referenced): void {
    (
      () ==> {
        $shadowed = false || $referenced;
      }
    );
  }

  public function foo(): void {
    $shadowed = true;
    $referenced = true; // should become a param to the extracted method
    /*range-start*/
    $this->${0:method0}($referenced);
    /*range-end*/
    $z = $shadowed;
  }
}

