Code actions available:
------------------------------------------
Extract into method (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 3, "character": 0 }
          },
          "newText": "  private function method0(int $x): int {\n    $y = $x + 1;\n    $z = $y + 1;\n    return $z;\n  }\n\n"
        },
        {
          "range": {
            "start": { "line": 8, "character": 4 },
            "end": { "line": 9, "character": 16 }
          },
          "newText": "$z = $this->method0($x);"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class A {
  private function method0(int $x): int {
    $y = $x + 1;
    $z = $y + 1;
    return $z;
  }

  public function foo(int $x): void {
    // The extracted method should *NOT* contain snippets (like `${0:placeholder}`),
    // because we are passing `--ide-code-actions-no-experimental-capabilities` to simulate
    // a client that doesn't have client experimental capability `snippetTextEdit`
    /*range-start*/
    $z = $this->method0($x);
    /*range-end*/
    $zz = $z;
  }
}

