WARN: File "dynamic_props2.php", line 10, characters 3-4:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
WARN: File "dynamic_props2.php", line 10, characters 3-13:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
WARN: File "dynamic_props2.php", line 10, characters 8-13:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
ERROR: File "dynamic_props2.php", line 5, characters 17-19:
Please add a type hint `public SomeType $f1` (Naming[2001])
ERROR: File "dynamic_props2.php", line 8, characters 10-10:
Was expecting a return type hint (Typing[4030])
