WARN: File "strict_method_call.php", line 7, characters 3-7:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
ERROR: File "strict_method_call.php", line 3, characters 10-12:
Was expecting a return type hint (Typing[4030])
