WARN: File "strict_call_tany2.php", line 18, characters 3-11:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
WARN: File "strict_call_tany2.php", line 18, characters 3-16:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
WARN: File "strict_call_tany2.php", line 18, characters 14-16:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
ERROR: File "strict_call_tany2.php", line 13, characters 19-21:
Was expecting a return type hint (Typing[4030])
