Code actions available:
------------------------------------------
Inline variable $x (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Inline variable $x",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 4, "character": 0 },
            "end": { "line": 5, "character": 0 }
          },
          "newText": ""
        },
        {
          "range": {
            "start": { "line": 5, "character": 29 },
            "end": { "line": 5, "character": 31 }
          },
          "newText": "$y"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function foo(): void {
     $y = 3;
     var_dump(/*range-start*/$y/*range-end*/);
}

