Code actions available:
------------------------------------------
Inline variable $x (CodeActionKind: "refactor") SELECTED
Devmate Quick Fix - This type is not permitted as an expression tree visitor. It is not included in `allowed_expression_tree_visitors` in `.hhconfig`, and this file does not contain `<<file:__EnableUnstableFeatures('expression_trees')>>`. (CodeActionKind: "quickfix")
Devmate Agent Fix - This type is not permitted as an expression tree visitor. It is not included in `allowed_expression_tree_visitors` in `.hhconfig`, and this file does not contain `<<file:__EnableUnstableFeatures('expression_trees')>>`. (CodeActionKind: "quickfix")

JSON for selected code action:
------------------------------------------
{
  "title": "Inline variable $x",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 4, "character": 0 },
            "end": { "line": 5, "character": 0 }
          },
          "newText": ""
        },
        {
          "range": {
            "start": { "line": 5, "character": 18 },
            "end": { "line": 5, "character": 20 }
          },
          "newText": "5"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function foo(): void {
  ExampleDsl`() ==> {
   /*range-start*/5/*range-end*/;
  }`;
}

