WARN: File "shape_structural_subtyping_of_empty_shape.php", line 9, characters 15-26:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
ERROR: File "shape_structural_subtyping_of_empty_shape.php", line 3, characters 10-19:
Was expecting a return type hint (Typing[4030])
ERROR: File "shape_structural_subtyping_of_empty_shape.php", line 8, characters 10-47:
Invalid return type (Typing[4057])
  File "shape_structural_subtyping_of_empty_shape.php", line 7, characters 27-33:
  The field `test` is missing
  File "shape_structural_subtyping_of_empty_shape.php", line 9, characters 5-10:
  The field `test` is required here
