Code actions available:
------------------------------------------
Flip around comma (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Flip around comma",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 9 },
            "end": { "line": 3, "character": 60 }
          },
          "newText": "\"b\" => true, \"a\" => true"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function foo(): void {
    dict["b" => true, "a" => true];
}

