Code actions available:
------------------------------------------
Flip around comma (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Flip around comma",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 6 },
            "end": { "line": 3, "character": 38 }
          },
          "newText": "2, 1"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function foo(): void {
  bar(2, 1);
}

function bar(int $a, int $b): void {}

