Code actions available:
------------------------------------------
Flip around comma (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Flip around comma",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 4 },
            "end": { "line": 3, "character": 46 }
          },
          "newText": "int $b, int $a"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function foo(): void {
  ((int $b, int $a) ==> {

  })(1, 2);
}

