Code actions available:
------------------------------------------
Add local type hint for $the_variable (CodeActionKind: "refactor") SELECTED
Devmate Quick Fix - Hack does not support top level statements. Use the `__EntryPoint` attribute on a function instead (CodeActionKind: "quickfix")
Devmate Agent Fix - Hack does not support top level statements. Use the `__EntryPoint` attribute on a function instead (CodeActionKind: "quickfix")

JSON for selected code action:
------------------------------------------
{
  "title": "Add local type hint for $the_variable",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 4, "character": 15 },
            "end": { "line": 4, "character": 28 }
          },
          "newText": "let $the_variable : int "
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh
<<file:__EnableUnstableFeatures('typed_local_variables')>>

// convert to `let $the_variable: int = 1;`
/*range-start*/let $the_variable : int /*range-end*/ = 1;

