Code actions available:
------------------------------------------
Add local type hint for $the_variable (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Add local type hint for $the_variable",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 5, "character": 17 },
            "end": { "line": 5, "character": 30 }
          },
          "newText": "let $the_variable : int "
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh
<<file:__EnableUnstableFeatures('typed_local_variables')>>

function f() : void {
  // convert to `let $the_variable: int = 1;`
  /*range-start*/let $the_variable : int /*range-end*/ = 1;
}

