Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
Add local type hint for $y (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Add local type hint for $y",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 6, "character": 19 },
            "end": { "line": 6, "character": 21 }
          },
          "newText": "let $y : int "
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh
<<file:__EnableUnstableFeatures('typed_local_variables')>>

function f(int $x) : void {
  $x = () ==> {
    // add a type hint for `$y`
    /*range-start*/let $y : int  = 3;/*range-end*/
  };
}

