Code actions available:
------------------------------------------
Add stubs for missing interface methods (CodeActionKind: "quickfix") SELECTED
Add stubs for missing inherited methods (CodeActionKind: "quickfix") SELECTED

Multiple code action titles match prefix: 'Add '

Code action title: Add stubs for missing interface methods

JSON for selected code action:
------------------------------------------
{
  "title": "Add stubs for missing interface methods",
  "kind": "quickfix",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 17, "character": 0 },
            "end": { "line": 17, "character": 0 }
          },
          "newText": "\n  public static function i(): int {}\n"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

trait FooTrait {
  abstract public function bar(): void;
  abstract public function baz(): void;
}

abstract class AbstractBar {
  abstract public function baf(): void;
}

interface I {
  public static function i(): int;
}

class Foo extends AbstractBar implements I {
  use FooTrait;

  public static function i(): int {}
/*range-start*/}/*range-end*/


Code action title: Add stubs for missing inherited methods

JSON for selected code action:
------------------------------------------
{
  "title": "Add stubs for missing inherited methods",
  "kind": "quickfix",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 17, "character": 0 },
            "end": { "line": 17, "character": 0 }
          },
          "newText": "\n  <<__Override>>\n  public function baf(): void {}\n\n  <<__Override>>\n  public function bar(): void {}\n\n  <<__Override>>\n  public function baz(): void {}\n"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

trait FooTrait {
  abstract public function bar(): void;
  abstract public function baz(): void;
}

abstract class AbstractBar {
  abstract public function baf(): void;
}

interface I {
  public static function i(): int;
}

class Foo extends AbstractBar implements I {
  use FooTrait;

  <<__Override>>
  public function baf(): void {}

  <<__Override>>
  public function bar(): void {}

  <<__Override>>
  public function baz(): void {}
/*range-start*/}/*range-end*/

