Code actions available:
------------------------------------------
Add stubs for missing interface methods (CodeActionKind: "quickfix") SELECTED
Devmate Quick Fix - This interface is not properly implemented (CodeActionKind: "quickfix")
Devmate Agent Fix - This interface is not properly implemented (CodeActionKind: "quickfix")

JSON for selected code action:
------------------------------------------
{
  "title": "Add stubs for missing interface methods",
  "kind": "quickfix",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 9, "character": 0 },
            "end": { "line": 9, "character": 0 }
          },
          "newText": "\n  public function bar(int $x, shape(\"y\" => vec<int>) $s, shape(...) $_, IFoo $other, dynamic $d, mixed $m, (float, num) $tuple, T $t, Vector<null> $v, ?arraykey $ak, nothing $_, mixed $_, int ...$args): void {}\n"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

interface IFoo {
  public function bar<T>(int $x, shape('y' => vec<int>) $s, shape(...) $_, IFoo $other, dynamic $d, mixed $m, (float, num) $tuple, T $t, Vector<null> $v, ?arraykey $ak, nothing $_, ?nonnull $_, int ...$args): void;
}

class Foo implements IFoo {
                   // ^ at-caret
  public function otherMethod(): void {}

  public function bar(int $x, shape("y" => vec<int>) $s, shape(...) $_, IFoo $other, dynamic $d, mixed $m, (float, num) $tuple, T $t, Vector<null> $v, ?arraykey $ak, nothing $_, mixed $_, int ...$args): void {}

}

