Code actions available:
------------------------------------------
Add stubs for missing inherited methods (CodeActionKind: "quickfix") SELECTED
Devmate Quick Fix - This class must be declared `abstract`, or provide an implementation for the abstract method `baz` (CodeActionKind: "quickfix")
Devmate Agent Fix - This class must be declared `abstract`, or provide an implementation for the abstract method `baz` (CodeActionKind: "quickfix")
Devmate Quick Fix - This class must be declared `abstract`, or provide an implementation for the abstract method `bar` (CodeActionKind: "quickfix")
Devmate Agent Fix - This class must be declared `abstract`, or provide an implementation for the abstract method `bar` (CodeActionKind: "quickfix")

JSON for selected code action:
------------------------------------------
{
  "title": "Add stubs for missing inherited methods",
  "kind": "quickfix",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 10, "character": 0 },
            "end": { "line": 10, "character": 0 }
          },
          "newText": "\n  <<__Override>>\n  public function bar(): void {}\n\n  <<__Override>>\n  public function baz(): void {}\n"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

trait FooTrait {
  abstract public function bar(): void;
  abstract public function baz(): void;
}

class Foo {
//      ^ at-caret
  use FooTrait;

  <<__Override>>
  public function bar(): void {}

  <<__Override>>
  public function baz(): void {}
}

