Code actions available:
------------------------------------------
Add override for MyClass::foo (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Add override for MyClass::foo",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 6, "character": 31 },
            "end": { "line": 6, "character": 31 }
          },
          "newText": "\n  <<__Override>>\n  public static async function foo(): Awaitable<void> {\n    \n  }\n\n"
        }
      ]
    }
  },
  "command": {
    "title": "Set Cursor Selection",
    "command": "hack.setSelection",
    "arguments": [
      {
        "start": { "line": 9, "character": 4 },
        "end": { "line": 9, "character": 4 }
      },
      {
        "title": "Trigger Inline Suggest",
        "command": "editor.action.inlineSuggest.trigger",
        "arguments": []
      }
    ]
  }
}

Applied edit for code action:
------------------------------------------
<?hh

abstract class MyClass {
  abstract public static function foo(): Awaitable<void>;
}

class MyChild extends MyClass {
  <<__Override>>
  public static async function foo(): Awaitable<void> {
    >||<
  }


                     // ^ at-caret
}

