Code actions available:
------------------------------------------
Add override for MyParent::methodInGrandParent (CodeActionKind: "refactor") SELECTED
Add override for MyParent::methodInParent (CodeActionKind: "refactor") SELECTED

Multiple code action titles match prefix: 'Add '

Code action title: Add override for MyParent::methodInGrandParent

JSON for selected code action:
------------------------------------------
{
  "title": "Add override for MyParent::methodInGrandParent",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 14, "character": 32 },
            "end": { "line": 14, "character": 32 }
          },
          "newText": "\n  <<__Override>>\n  public function methodInGrandParent(): void {\n    \n  }\n\n"
        }
      ]
    }
  },
  "command": {
    "title": "Set Cursor Selection",
    "command": "hack.setSelection",
    "arguments": [
      {
        "start": { "line": 17, "character": 4 },
        "end": { "line": 17, "character": 4 }
      },
      {
        "title": "Trigger Inline Suggest",
        "command": "editor.action.inlineSuggest.trigger",
        "arguments": []
      }
    ]
  }
}

Applied edit for code action:
------------------------------------------
<?hh

abstract class MyGrandParent {
  abstract public function methodInGrandParent(): void;
}

abstract class MyParent extends MyGrandParent {
  abstract public function methodInParent(): void;
}

trait MyTrait {
  abstract public function methodInTrait(): void;
}

class MyClass extends MyParent {
  <<__Override>>
  public function methodInGrandParent(): void {
    >||<
  }


  //                  ^ at-caret
  use MyTrait;
}


Code action title: Add override for MyParent::methodInParent

JSON for selected code action:
------------------------------------------
{
  "title": "Add override for MyParent::methodInParent",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 14, "character": 32 },
            "end": { "line": 14, "character": 32 }
          },
          "newText": "\n  <<__Override>>\n  public function methodInParent(): void {\n    \n  }\n\n"
        }
      ]
    }
  },
  "command": {
    "title": "Set Cursor Selection",
    "command": "hack.setSelection",
    "arguments": [
      {
        "start": { "line": 17, "character": 4 },
        "end": { "line": 17, "character": 4 }
      },
      {
        "title": "Trigger Inline Suggest",
        "command": "editor.action.inlineSuggest.trigger",
        "arguments": []
      }
    ]
  }
}

Applied edit for code action:
------------------------------------------
<?hh

abstract class MyGrandParent {
  abstract public function methodInGrandParent(): void;
}

abstract class MyParent extends MyGrandParent {
  abstract public function methodInParent(): void;
}

trait MyTrait {
  abstract public function methodInTrait(): void;
}

class MyClass extends MyParent {
  <<__Override>>
  public function methodInParent(): void {
    >||<
  }


  //                  ^ at-caret
  use MyTrait;
}

