Code actions available:
------------------------------------------
Add override for FooParent::bar (CodeActionKind: "refactor") SELECTED
Add override for FooParent::baz (CodeActionKind: "refactor") SELECTED

Multiple code action titles match prefix: 'Add '

Code action title: Add override for FooParent::bar

JSON for selected code action:
------------------------------------------
{
  "title": "Add override for FooParent::bar",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 7, "character": 29 },
            "end": { "line": 7, "character": 29 }
          },
          "newText": "\n  <<__Override>>\n  public function bar(): void {\n    \n  }\n\n"
        }
      ]
    }
  },
  "command": {
    "title": "Set Cursor Selection",
    "command": "hack.setSelection",
    "arguments": [
      {
        "start": { "line": 10, "character": 4 },
        "end": { "line": 10, "character": 4 }
      },
      {
        "title": "Trigger Inline Suggest",
        "command": "editor.action.inlineSuggest.trigger",
        "arguments": []
      }
    ]
  }
}

Applied edit for code action:
------------------------------------------
<?hh

abstract class FooParent {
  abstract public function bar(): void;
  abstract public function baz(): void;
}

class Foo extends FooParent {
  <<__Override>>
  public function bar(): void {
    >||<
  }

}
  //                  ^ at-caret


Code action title: Add override for FooParent::baz

JSON for selected code action:
------------------------------------------
{
  "title": "Add override for FooParent::baz",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 7, "character": 29 },
            "end": { "line": 7, "character": 29 }
          },
          "newText": "\n  <<__Override>>\n  public function baz(): void {\n    \n  }\n\n"
        }
      ]
    }
  },
  "command": {
    "title": "Set Cursor Selection",
    "command": "hack.setSelection",
    "arguments": [
      {
        "start": { "line": 10, "character": 4 },
        "end": { "line": 10, "character": 4 }
      },
      {
        "title": "Trigger Inline Suggest",
        "command": "editor.action.inlineSuggest.trigger",
        "arguments": []
      }
    ]
  }
}

Applied edit for code action:
------------------------------------------
<?hh

abstract class FooParent {
  abstract public function bar(): void;
  abstract public function baz(): void;
}

class Foo extends FooParent {
  <<__Override>>
  public function baz(): void {
    >||<
  }

}
  //                  ^ at-caret

