ERROR: File "method_swap_error.php", line 17, characters 14-23:
Invalid argument (Typing[4110])
  File "method_swap_error.php", line 12, characters 24-30:
  Expected `<expr#19>::T`
  File "method_swap_error.php", line 17, characters 5-7:
    where `<expr#19>` is a reference to this expression
  File "method_swap_error.php", line 8, characters 26-32:
  But got `<expr#20>::T as X::T`
  File "method_swap_error.php", line 17, characters 14-16:
    where `<expr#20>` is a reference to this expression
ERROR: File "method_swap_error.php", line 17, characters 14-23:
Invalid argument (Typing[4110])
  File "method_swap_error.php", line 12, characters 24-30:
  Expected `<expr#19>::T`
  File "method_swap_error.php", line 17, characters 5-7:
    where `<expr#19>` is a reference to this expression
  File "method_swap_error.php", line 8, characters 26-32:
  But got `X::T where \X::T super <expr#20>::T, \X::T super this::T, \X::T as arraykey`
  File "method_swap_error.php", line 17, characters 14-16:
    where `<expr#20>` is a reference to this expression
ERROR: File "method_swap_error.php", line 17, characters 14-23:
Invalid argument (Typing[4110])
  File "method_swap_error.php", line 12, characters 24-30:
  Expected `<expr#19>::T`
  File "method_swap_error.php", line 17, characters 5-7:
    where `<expr#19>` is a reference to this expression
  File "method_swap_error.php", line 8, characters 26-32:
  But got `arraykey`
  File "method_swap_error.php", line 17, characters 14-16:
    where `<expr#20>` is a reference to this expression
