Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor") SELECTED
Devmate Quick Fix - Typing error (CodeActionKind: "quickfix")
Devmate Agent Fix - Typing error (CodeActionKind: "quickfix")

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into variable",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 8, "character": 4 },
            "end": { "line": 11, "character": 21 }
          },
          "newText": "$${0:placeholder0} = 300\n      //\n      +\n      2;\n    return /*range-start*/$${0:placeholder0}/*range-end*/;"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

<<__EntryPoint>>
function main(): void {
  $z = 100 +
    () ==>{
    $x = 3;
    // expect variable extracted to here
    $${0:placeholder0} = 300
      //
      +
      2;
    return /*range-start*/$${0:placeholder0}/*range-end*/;
}
}

