Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into variable",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 4, "character": 19 },
            "end": { "line": 4, "character": 24 }
          },
          "newText": "{\n    $${0:placeholder0} = 3 + 3;\n    return $${0:placeholder0};\n  }"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function foo(): void {
  (($a = () ==> {}) ==>
    /*range-start*/{
    $${0:placeholder0} = 3 + 3;
    return $${0:placeholder0};
  }/*range-end*/
  );
}

