Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into variable",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 5, "character": 2 },
            "end": { "line": 9, "character": 20 }
          },
          "newText": "$${0:placeholder0} = 3 * 2\n  * 7;\n  $z = 100 +\n  /* */\n  3 *\n  (/*range-start*/$${0:placeholder0}/*range-end*/);"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

<<__EntryPoint>>
function main(): void {
  // expect variable extracted to here
  $${0:placeholder0} = 3 * 2
  * 7;
  $z = 100 +
  /* */
  3 *
  (/*range-start*/$${0:placeholder0}/*range-end*/);
}

