Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor") SELECTED
Devmate Quick Fix - Typing error (CodeActionKind: "quickfix")
Devmate Agent Fix - Typing error (CodeActionKind: "quickfix")

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into variable",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 6, "character": 25 },
            "end": { "line": 6, "character": 32 }
          },
          "newText": "{\n    $${0:placeholder0} = 300 + 2;\n    return $${0:placeholder0};\n  }"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

<<__EntryPoint>>
function main(): void {
  // No variable extraction expected
  $z = 100 +
    () ==>/*range-start*/{
    $${0:placeholder0} = 300 + 2;
    return $${0:placeholder0};
  }/*range-end*/
}

