Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into variable",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 13, "character": 2 },
            "end": { "line": 13, "character": 75 }
          },
          "newText": "$${0:placeholder0} = $a->toggle_mut_and_ret_false();\n  $x = $a->b || /*range-start*/$${0:placeholder0}/*range-end*/;"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class A {
  public function __construct(public bool $b) {}
  public function toggle_mut_and_ret_false(): bool {
    $this->b = !$this->b;
    return false;
  }
}

<<__EntryPoint>>
function main(): void {
  $a = new A(false);
  $${0:placeholder0} = $a->toggle_mut_and_ret_false();
  $x = $a->b || /*range-start*/$${0:placeholder0}/*range-end*/;
  var_dump($x); // false

  // The refactor can change the meaning of the code in a way that is hard to detect.
  // IntelliJ Kotlin has the same unsafety:  https://pl.kotl.in/isarlHogA
  // $a = new A(false);
  // $placeholder_ = $a->toggle_mut_and_ret_false();
  // $x = $a->b || $placeholder_;
  // var_dump($x); // true
}

