Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into variable",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 4, "character": 4 },
            "end": { "line": 4, "character": 43 }
          },
          "newText": "$${0:placeholder0} = 3 + 3;\n    $x = /*range-start*/$${0:placeholder0}/*range-end*/;"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function main(): void {
  (() ==> {
    $${0:placeholder0} = 3 + 3;
    $x = /*range-start*/$${0:placeholder0}/*range-end*/;
  })();
}

