Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into variable",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 5, "character": 2 },
            "end": { "line": 5, "character": 45 }
          },
          "newText": "$${0:placeholder2} = 1 * 2;\n  $x = /*range-start*/$${0:placeholder2}/*range-end*/ + 3;"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function main(): void {
  $placeholder1 = "";
  // expecting `$placeholder2` defined here
  $${0:placeholder2} = 1 * 2;
  $x = /*range-start*/$${0:placeholder2}/*range-end*/ + 3;
}

