Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into variable",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 2 },
            "end": { "line": 3, "character": 45 }
          },
          "newText": "$${0:placeholder0} = 1 * 2;\n  $x = /*range-start*/$${0:placeholder0}/*range-end*/ + 3;"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function main(string $placeholder_): void {
  $${0:placeholder0} = 1 * 2;
  $x = /*range-start*/$${0:placeholder0}/*range-end*/ + 3;
}

