Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into variable",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 24 },
            "end": { "line": 3, "character": 29 }
          },
          "newText": "{\n    $${0:placeholder0} = 3 + 2;\n    return $${0:placeholder0};\n  }"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function main(): void {
  () ==> /*range-start*/{
    $${0:placeholder0} = 3 + 2;
    return $${0:placeholder0};
  }/*range-end*/;
}

