Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract into variable",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 5, "character": 20 },
            "end": { "line": 5, "character": 65 }
          },
          "newText": "{\n    $${0:placeholder0} = 1 + 2;\n    return 1 < 2 ? /*range-start*/$${0:placeholder0}/*range-end*/ : 0;\n  }"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

function take_mixed(mixed $_): void {}

function main(): void {
  take_mixed(() ==> {
    $${0:placeholder0} = 1 + 2;
    return 1 < 2 ? /*range-start*/$${0:placeholder0}/*range-end*/ : 0;
  });
}

