Code actions available:
------------------------------------------
await expression (CodeActionKind: "refactor") SELECTED
Extract into variable (CodeActionKind: "refactor")
Devmate Quick Fix - Invalid return type (CodeActionKind: "quickfix")
Devmate Agent Fix - Invalid return type (CodeActionKind: "quickfix")
Devmate Quick Fix - Typing error (CodeActionKind: "quickfix")
Devmate Agent Fix - Typing error (CodeActionKind: "quickfix")

JSON for selected code action:
------------------------------------------
{
  "title": "await expression",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 9, "character": 11 },
            "end": { "line": 9, "character": 11 }
          },
          "newText": "async "
        },
        {
          "range": {
            "start": { "line": 10, "character": 6 },
            "end": { "line": 10, "character": 53 }
          },
          "newText": "$_ = /*range-start*/await gen_int()/*range-end*/ + 3;"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

async function gen_int(): Awaitable<int> {
  return 1;
}

function example(): Awaitable<mixed> {
  return () ==> {
    // `asnyc` should be added to this lambda, not the one above
    return async () ==> {
      $_ = /*range-start*/await gen_int()/*range-end*/ + 3;
    }
  }
}

