Code actions available:
------------------------------------------
await expression (CodeActionKind: "refactor") SELECTED
Extract into variable (CodeActionKind: "refactor")

JSON for selected code action:
------------------------------------------
{
  "title": "await expression",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 12, "character": 16 },
            "end": { "line": 12, "character": 20 }
          },
          "newText": "Awaitable<void>"
        },
        {
          "range": {
            "start": { "line": 12, "character": 0 },
            "end": { "line": 12, "character": 0 }
          },
          "newText": "async "
        },
        {
          "range": {
            "start": { "line": 14, "character": 17 },
            "end": { "line": 14, "character": 48 }
          },
          "newText": "(await gen_foo())/*range-end*/->meth();"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class Foo() {
  public function meth(): int {
    return 1;
  }
}

async function gen_foo(): Awaitable<Foo> {
  return new Foo();
}

async function foo(): Awaitable<void> {
  // The refactoring should generate `(await gen_foo())->meth()`
  /*range-start*/(await gen_foo())/*range-end*/->meth();
}

