ERROR: File "trait_require_class.php", line 4, characters 7-8:
Trait T1 requires class C but C does not use it. Either use the trait or delete it. (Typing[4466])
  File "trait_require_class.php", line 13, characters 7-7:
  Class C is defined here.
  File "trait_require_class.php", line 5, characters 17-17:
  The require class requirement is here.
ERROR: File "trait_require_class.php", line 8, characters 7-8:
Trait T2 requires class C but C does not use it. Either use the trait or delete it. (Typing[4466])
  File "trait_require_class.php", line 13, characters 7-7:
  Class C is defined here.
  File "trait_require_class.php", line 9, characters 17-17:
  The require class requirement is here.
ERROR: File "trait_require_class.php", line 8, characters 7-8:
Trait T2 requires class D but D does not use it. Either use the trait or delete it. (Typing[4466])
  File "trait_require_class.php", line 14, characters 7-7:
  Class D is defined here.
  File "trait_require_class.php", line 10, characters 17-17:
  The require class requirement is here.
