File "complex_literal_key.php--main.php", line 17, characters 3-13:
  dict<((arraykey & class<A>) | classname<B>), int>
File "complex_literal_key.php--main.php", line 24, characters 3-13:
  dict<((arraykey & class<A>) | string), int>
ERROR: File "complex_literal_key.php--main.php", line 16, characters 8-20:
Invalid index type for this dict (Typing[4110])
  File "complex_literal_key.php--main.php", line 16, characters 13-14:
  Expected `arraykey` because only array keys can be used to index into a `Map`, `dict`, `darray`, `Set`, or `keyset`
  File "complex_literal_key.php--main.php", line 14, characters 31-38:
  But got `class<A>`
ERROR: File "complex_literal_key.php--main.php", line 23, characters 8-20:
Invalid index type for this dict (Typing[4110])
  File "complex_literal_key.php--main.php", line 23, characters 13-14:
  Expected `arraykey` because only array keys can be used to index into a `Map`, `dict`, `darray`, `Set`, or `keyset`
  File "complex_literal_key.php--main.php", line 21, characters 28-35:
  But got `class<A>`
ERROR: File "complex_literal_key.php--main.php", line 28, characters 8-20:
Invalid index type for this dict (Typing[4110])
  File "complex_literal_key.php--main.php", line 28, characters 13-14:
  Expected `arraykey` because only array keys can be used to index into a `Map`, `dict`, `darray`, `Set`, or `keyset`
  File "complex_literal_key.php--main.php", line 27, characters 39-39:
  But got `T as class<A>`
ERROR: File "complex_literal_key.php--main.php", line 28, characters 8-20:
Invalid index type for this dict (Typing[4110])
  File "complex_literal_key.php--main.php", line 28, characters 13-14:
  Expected `arraykey` because only array keys can be used to index into a `Map`, `dict`, `darray`, `Set`, or `keyset`
  File "complex_literal_key.php--main.php", line 27, characters 39-39:
  But got `class<A>`
  File "complex_literal_key.php--main.php", line 27, characters 29-36:
    by the definition of `T`
ERROR: File "complex_literal_key.php--main.php", line 35, characters 10-22:
Invalid index type for this dict (Typing[4110])
  File "complex_literal_key.php--main.php", line 35, characters 15-16:
  Expected `arraykey` because only array keys can be used to index into a `Map`, `dict`, `darray`, `Set`, or `keyset`
  File "complex_literal_key.php--main.php", line 34, characters 23-32:
  But got `HasTypeConstant::TCls where \HasTypeConstant::TCls super this::TCls, \HasTypeConstant::TCls as class<A>`
ERROR: File "complex_literal_key.php--main.php", line 35, characters 10-22:
Invalid index type for this dict (Typing[4110])
  File "complex_literal_key.php--main.php", line 35, characters 15-16:
  Expected `arraykey` because only array keys can be used to index into a `Map`, `dict`, `darray`, `Set`, or `keyset`
  File "complex_literal_key.php--main.php", line 34, characters 23-32:
  But got `class<A>`
ERROR: File "complex_literal_key.php--main.php", line 35, characters 10-22:
Invalid index type for this dict (Typing[4110])
  File "complex_literal_key.php--main.php", line 35, characters 15-16:
  Expected `arraykey` because only array keys can be used to index into a `Map`, `dict`, `darray`, `Set`, or `keyset`
  File "complex_literal_key.php--main.php", line 34, characters 23-32:
  But got `this::TCls as HasTypeConstant::TCls`
ERROR: File "complex_literal_key.php--main.php", line 40, characters 8-20:
Invalid index type for this dict (Typing[4110])
  File "complex_literal_key.php--main.php", line 40, characters 13-14:
  Expected `arraykey` because only array keys can be used to index into a `Map`, `dict`, `darray`, `Set`, or `keyset`
  File "complex_literal_key.php--main.php", line 39, characters 25-34:
  But got `class<A>`
  File "complex_literal_key.php--defs.php", line 12, characters 23-30:
    by the definition of `OpaqueClsA`
