WARN: File "dynamic_obj_get_non_dynamic.bad.php", line 80, characters 3-15:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 18, characters 3-7:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `dict<string, int>` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 17, characters 24-40:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 22, characters 3-7:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `dict<string, int>` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 21, characters 21-37:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 26, characters 3-7:
Dynamic access of a method is only permitted on a receiver of type `dynamic`, but this receiver has type `dict<string, int>` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 25, characters 22-38:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 30, characters 3-8:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `shape('foo' => int)` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 29, characters 25-43:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 34, characters 3-8:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `(C | dict<string, int>)` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 33, characters 25-47:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 38, characters 3-7:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `~dict<string, int>` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 37, characters 29-46:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 42, characters 3-7:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `T` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 41, characters 62-62:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 46, characters 3-9:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `?C` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 45, characters 35-36:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 50, characters 3-7:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `?dict<string, int>` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 49, characters 33-50:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 54, characters 3-9:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `?C` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 53, characters 35-36:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 58, characters 3-9:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `C` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 57, characters 26-26:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 62, characters 3-9:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `C` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 61, characters 32-32:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 66, characters 3-9:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `T` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 65, characters 48-48:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 70, characters 3-9:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `T` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 69, characters 51-51:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 74, characters 3-9:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `?dynamic` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 73, characters 36-43:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 77, characters 10-20:
Was expecting a return type hint (Typing[4030])
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 89, characters 3-9:
Typing error (Typing[4053])
  File "dynamic_obj_get_non_dynamic.bad.php", line 89, characters 12-18:
  No property `missing` in `ErrorTyvarReceiver`
  File "dynamic_obj_get_non_dynamic.bad.php", line 86, characters 3-20:
  This is why I think it is an object of type ErrorTyvarReceiver
  File "dynamic_obj_get_non_dynamic.bad.php", line 83, characters 7-24:
  Declaration of `ErrorTyvarReceiver` is here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 95, characters 3-9:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `((nonnull & dynamic) | C)` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 93, characters 3-27:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 103, characters 3-7:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `dict<string, int>` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 103, characters 10-18:
  Did you mean `->property` instead?
  File "dynamic_obj_get_non_dynamic.bad.php", line 100, characters 3-19:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 107, characters 3-8:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `mixed` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 107, characters 11-19:
  Did you mean `->property` instead?
  File "dynamic_obj_get_non_dynamic.bad.php", line 106, characters 34-38:
  The receiver's type is defined here
ERROR: File "dynamic_obj_get_non_dynamic.bad.php", line 114, characters 3-8:
Dynamic access of a property is only permitted on a receiver of type `dynamic`, but this receiver has type `nonnull` (Typing[4525])
  File "dynamic_obj_get_non_dynamic.bad.php", line 114, characters 11-19:
  Did you mean `->property` instead?
  File "dynamic_obj_get_non_dynamic.bad.php", line 111, characters 3-9:
  The receiver's type is defined here
