WARN: File "dynamic_obj_get_non_dynamic.good.php", line 15, characters 13-27:
Property accessed on a value of type `dynamic` (Warn[12042])
  File "dynamic_obj_get_non_dynamic.good.php", line 14, characters 27-33:
  This expression has type `dynamic`
WARN: File "dynamic_obj_get_non_dynamic.good.php", line 29, characters 14-28:
Property accessed on a value of type `dynamic` (Warn[12042])
  File "dynamic_obj_get_non_dynamic.good.php", line 28, characters 36-42:
  This expression has type `dynamic`
WARN: File "dynamic_obj_get_non_dynamic.good.php", line 47, characters 11-25:
Property accessed on a value of type `(dynamic & dict<string, int>)` (Warn[12042])
  File "dynamic_obj_get_non_dynamic.good.php", line 45, characters 4-10:
  This expression has type `dynamic`
WARN: File "dynamic_obj_get_non_dynamic.good.php", line 51, characters 12-26:
Property accessed on a value of type `(dynamic & int)` (Warn[12042])
  File "dynamic_obj_get_non_dynamic.good.php", line 50, characters 32-38:
  This expression has type `dynamic`
WARN: File "dynamic_obj_get_non_dynamic.good.php", line 55, characters 13-27:
Property accessed on a value of type `(dynamic & nonnull)` (Warn[12042])
  File "dynamic_obj_get_non_dynamic.good.php", line 54, characters 36-42:
  This expression has type `dynamic`
WARN: File "dynamic_obj_get_non_dynamic.good.php", line 59, characters 13-27:
Property accessed on a value of type `dynamic` (Warn[12042])
  File "dynamic_obj_get_non_dynamic.good.php", line 58, characters 39-45:
  This expression has type `dynamic`
WARN: File "dynamic_obj_get_non_dynamic.good.php", line 66, characters 11-19:
Property accessed on a value of type `(dynamic & nonnull)` (Warn[12042])
  File "dynamic_obj_get_non_dynamic.good.php", line 63, characters 4-10:
  This expression has type `dynamic`
WARN: File "dynamic_obj_get_non_dynamic.good.php", line 73, characters 23-29:
Indexing into a value of type `dynamic` (Warn[12040])
  File "dynamic_obj_get_non_dynamic.good.php", line 70, characters 3-9:
  This expression has type `dynamic`
WARN: File "dynamic_obj_get_non_dynamic.good.php", line 74, characters 13-27:
Property accessed on a value of type `(dynamic & ~C)` (Warn[12042])
  File "dynamic_obj_get_non_dynamic.good.php", line 73, characters 23-39:
  This expression has type `dynamic`
WARN: File "dynamic_obj_get_non_dynamic.good.php", line 75, characters 12-20:
Property accessed on a value of type `(dynamic & ~C)` (Warn[12042])
  File "dynamic_obj_get_non_dynamic.good.php", line 73, characters 23-39:
  This expression has type `dynamic`
