Code actions available:
------------------------------------------
Inline variable $sh (CodeActionKind: "refactor")
Extract shape type (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract shape type",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 2, "character": 0 },
            "end": { "line": 2, "character": 0 }
          },
          "newText": "type T${0:placeholder_} = shape('a' => int);\n\n"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

type T${0:placeholder_} = shape('a' => int);

function foo(vec<shape('a' => int)> $v): void {
  $sh = $v[0];
  // This test may fail if we start using the tast under Sound Dynamic (https://fburl.com/code/9lkro66x).
  // If that happens, then try stripping "like types" (`~shape()` to `shape()`)
  /*range-start*/$sh/*range-end*/;
}

