Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor")
Extract shape type (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract shape type",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 2, "character": 0 },
            "end": { "line": 2, "character": 0 }
          },
          "newText": "type T${0:placeholder_} = shape(?'a' => int, 'b' => int, ...);\n\n"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

type T${0:placeholder_} = shape(?'a' => int, 'b' => int, ...);

class C {
  public function foo(shape(?"a" => int, ...) $sh): void {
    $sh["b"] = 3;
    $x =/*range-start*/$sh/*range-end*/;
  }
}

