{
  "kind": "script",
  "script_declarations": {
    "kind": "list",
    "elements": [
      {
        "kind": "markup_section",
        "markup_suffix": {
          "kind": "markup_suffix",
          "markup_suffix_less_than_question": {
            "kind": "token",
            "token": {
              "kind": "<?",
              "text": "<?",
              "offset": 0,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 1
            }
          },
          "markup_suffix_name": {
            "kind": "token",
            "token": {
              "kind": "name",
              "text": "hh",
              "offset": 2,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 4,
                  "width": 1
                }
              ],
              "line_number": 1
            }
          }
        }
      },
      {
        "kind": "function_declaration",
        "function_declaration_header": {
          "kind": "function_declaration_header",
          "function_keyword": {
            "kind": "token",
            "token": {
              "kind": "function",
              "text": "function",
              "offset": 5,
              "leading_width": 1,
              "width": 8,
              "trailing_width": 1,
              "leading": [
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 5,
                  "width": 1
                }
              ],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 14,
                  "width": 1
                }
              ],
              "line_number": 3
            }
          },
          "function_name": {
            "kind": "token",
            "token": {
              "kind": "name",
              "text": "main",
              "offset": 15,
              "leading_width": 0,
              "width": 4,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 3
            }
          },
          "function_left_paren": {
            "kind": "token",
            "token": {
              "kind": "(",
              "text": "(",
              "offset": 19,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 3
            }
          },
          "function_right_paren": {
            "kind": "token",
            "token": {
              "kind": ")",
              "text": ")",
              "offset": 20,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 3
            }
          },
          "function_colon": {
            "kind": "token",
            "token": {
              "kind": ":",
              "text": ":",
              "offset": 21,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 22,
                  "width": 1
                }
              ],
              "line_number": 3
            }
          },
          "function_type": {
            "kind": "simple_type_specifier",
            "simple_type_specifier": {
              "kind": "token",
              "token": {
                "kind": "void",
                "text": "void",
                "offset": 23,
                "leading_width": 0,
                "width": 4,
                "trailing_width": 1,
                "leading": [],
                "trailing": [
                  {
                    "kind": "whitespace",
                    "text": " ",
                    "offset": 27,
                    "width": 1
                  }
                ],
                "line_number": 3
              }
            }
          }
        },
        "function_body": {
          "kind": "compound_statement",
          "compound_left_brace": {
            "kind": "token",
            "token": {
              "kind": "{",
              "text": "{",
              "offset": 28,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 29,
                  "width": 1
                }
              ],
              "line_number": 3
            }
          },
          "compound_statements": {
            "kind": "list",
            "elements": [
              {
                "kind": "expression_statement",
                "expression_statement_expression": {
                  "kind": "binary_expression",
                  "binary_left_operand": {
                    "kind": "binary_expression",
                    "binary_left_operand": {
                      "kind": "literal",
                      "literal_expression": {
                        "kind": "token",
                        "token": {
                          "kind": "decimal_literal",
                          "text": "3",
                          "offset": 30,
                          "leading_width": 28,
                          "width": 1,
                          "trailing_width": 1,
                          "leading": [
                            {
                              "kind": "whitespace",
                              "text": "  ",
                              "offset": 30,
                              "width": 2
                            },
                            {
                              "kind": "single_line_comment",
                              "text": "// not a named argument",
                              "offset": 32,
                              "width": 23
                            },
                            {
                              "kind": "end_of_line",
                              "text": "\n",
                              "offset": 55,
                              "width": 1
                            },
                            {
                              "kind": "whitespace",
                              "text": "  ",
                              "offset": 56,
                              "width": 2
                            }
                          ],
                          "trailing": [
                            {
                              "kind": "whitespace",
                              "text": " ",
                              "offset": 59,
                              "width": 1
                            }
                          ],
                          "line_number": 5
                        }
                      }
                    },
                    "binary_operator": {
                      "kind": "token",
                      "token": {
                        "kind": "+",
                        "text": "+",
                        "offset": 60,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 1,
                        "leading": [],
                        "trailing": [
                          {
                            "kind": "whitespace",
                            "text": " ",
                            "offset": 61,
                            "width": 1
                          }
                        ],
                        "line_number": 5
                      }
                    },
                    "binary_right_operand": {
                      "kind": "token",
                      "token": {
                        "kind": "name",
                        "text": "x",
                        "offset": 62,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 1,
                        "leading": [],
                        "trailing": [
                          {
                            "kind": "whitespace",
                            "text": " ",
                            "offset": 63,
                            "width": 1
                          }
                        ],
                        "line_number": 5
                      }
                    }
                  },
                  "binary_operator": {
                    "kind": "token",
                    "token": {
                      "kind": "=",
                      "text": "=",
                      "offset": 64,
                      "leading_width": 0,
                      "width": 1,
                      "trailing_width": 1,
                      "leading": [],
                      "trailing": [
                        {
                          "kind": "whitespace",
                          "text": " ",
                          "offset": 65,
                          "width": 1
                        }
                      ],
                      "line_number": 5
                    }
                  },
                  "binary_right_operand": {
                    "kind": "literal",
                    "literal_expression": {
                      "kind": "token",
                      "token": {
                        "kind": "decimal_literal",
                        "text": "3",
                        "offset": 66,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 0,
                        "leading": [],
                        "trailing": [],
                        "line_number": 5
                      }
                    }
                  }
                },
                "expression_statement_semicolon": {
                  "kind": "token",
                  "token": {
                    "kind": ";",
                    "text": ";",
                    "offset": 67,
                    "leading_width": 0,
                    "width": 1,
                    "trailing_width": 1,
                    "leading": [],
                    "trailing": [
                      {
                        "kind": "end_of_line",
                        "text": "\n",
                        "offset": 68,
                        "width": 1
                      }
                    ],
                    "line_number": 5
                  }
                }
              },
              {
                "kind": "expression_statement",
                "expression_statement_expression": {
                  "kind": "binary_expression",
                  "binary_left_operand": {
                    "kind": "literal",
                    "literal_expression": {
                      "kind": "token",
                      "token": {
                        "kind": "decimal_literal",
                        "text": "4",
                        "offset": 69,
                        "leading_width": 28,
                        "width": 1,
                        "trailing_width": 1,
                        "leading": [
                          {
                            "kind": "whitespace",
                            "text": "  ",
                            "offset": 69,
                            "width": 2
                          },
                          {
                            "kind": "single_line_comment",
                            "text": "// not a named argument",
                            "offset": 71,
                            "width": 23
                          },
                          {
                            "kind": "end_of_line",
                            "text": "\n",
                            "offset": 94,
                            "width": 1
                          },
                          {
                            "kind": "whitespace",
                            "text": "  ",
                            "offset": 95,
                            "width": 2
                          }
                        ],
                        "trailing": [
                          {
                            "kind": "whitespace",
                            "text": " ",
                            "offset": 98,
                            "width": 1
                          }
                        ],
                        "line_number": 7
                      }
                    }
                  },
                  "binary_operator": {
                    "kind": "token",
                    "token": {
                      "kind": "+",
                      "text": "+",
                      "offset": 99,
                      "leading_width": 0,
                      "width": 1,
                      "trailing_width": 1,
                      "leading": [],
                      "trailing": [
                        {
                          "kind": "whitespace",
                          "text": " ",
                          "offset": 100,
                          "width": 1
                        }
                      ],
                      "line_number": 7
                    }
                  },
                  "binary_right_operand": {
                    "kind": "parenthesized_expression",
                    "parenthesized_expression_left_paren": {
                      "kind": "token",
                      "token": {
                        "kind": "(",
                        "text": "(",
                        "offset": 101,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 0,
                        "leading": [],
                        "trailing": [],
                        "line_number": 7
                      }
                    },
                    "parenthesized_expression_expression": {
                      "kind": "binary_expression",
                      "binary_left_operand": {
                        "kind": "token",
                        "token": {
                          "kind": "name",
                          "text": "y",
                          "offset": 102,
                          "leading_width": 0,
                          "width": 1,
                          "trailing_width": 1,
                          "leading": [],
                          "trailing": [
                            {
                              "kind": "whitespace",
                              "text": " ",
                              "offset": 103,
                              "width": 1
                            }
                          ],
                          "line_number": 7
                        }
                      },
                      "binary_operator": {
                        "kind": "token",
                        "token": {
                          "kind": "=",
                          "text": "=",
                          "offset": 104,
                          "leading_width": 0,
                          "width": 1,
                          "trailing_width": 1,
                          "leading": [],
                          "trailing": [
                            {
                              "kind": "whitespace",
                              "text": " ",
                              "offset": 105,
                              "width": 1
                            }
                          ],
                          "line_number": 7
                        }
                      },
                      "binary_right_operand": {
                        "kind": "literal",
                        "literal_expression": {
                          "kind": "token",
                          "token": {
                            "kind": "decimal_literal",
                            "text": "3",
                            "offset": 106,
                            "leading_width": 0,
                            "width": 1,
                            "trailing_width": 0,
                            "leading": [],
                            "trailing": [],
                            "line_number": 7
                          }
                        }
                      }
                    },
                    "parenthesized_expression_right_paren": {
                      "kind": "token",
                      "token": {
                        "kind": ")",
                        "text": ")",
                        "offset": 107,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 0,
                        "leading": [],
                        "trailing": [],
                        "line_number": 7
                      }
                    }
                  }
                },
                "expression_statement_semicolon": {
                  "kind": "token",
                  "token": {
                    "kind": ";",
                    "text": ";",
                    "offset": 108,
                    "leading_width": 0,
                    "width": 1,
                    "trailing_width": 1,
                    "leading": [],
                    "trailing": [
                      {
                        "kind": "end_of_line",
                        "text": "\n",
                        "offset": 109,
                        "width": 1
                      }
                    ],
                    "line_number": 7
                  }
                }
              }
            ]
          },
          "compound_right_brace": {
            "kind": "token",
            "token": {
              "kind": "}",
              "text": "}",
              "offset": 110,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 111,
                  "width": 1
                }
              ],
              "line_number": 8
            }
          }
        }
      },
      {
        "kind": "end_of_file",
        "end_of_file_token": {
          "kind": "token",
          "token": {
            "kind": "end_of_file",
            "text": "",
            "offset": 112,
            "leading_width": 0,
            "width": 0,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 9
          }
        }
      }
    ]
  }
}
