{
  "kind": "script",
  "script_declarations": {
    "kind": "list",
    "elements": [
      {
        "kind": "markup_section",
        "markup_suffix": {
          "kind": "markup_suffix",
          "markup_suffix_less_than_question": {
            "kind": "token",
            "token": {
              "kind": "<?",
              "text": "<?",
              "offset": 0,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 1
            }
          },
          "markup_suffix_name": {
            "kind": "token",
            "token": {
              "kind": "name",
              "text": "hh",
              "offset": 2,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 4,
                  "width": 1
                }
              ],
              "line_number": 1
            }
          }
        }
      },
      {
        "kind": "function_declaration",
        "function_declaration_header": {
          "kind": "function_declaration_header",
          "function_keyword": {
            "kind": "token",
            "token": {
              "kind": "function",
              "text": "function",
              "offset": 5,
              "leading_width": 36,
              "width": 8,
              "trailing_width": 1,
              "leading": [
                {
                  "kind": "single_line_comment",
                  "text": "// Optional must precede readonly.",
                  "offset": 5,
                  "width": 34
                },
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 39,
                  "width": 1
                },
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 40,
                  "width": 1
                }
              ],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 49,
                  "width": 1
                }
              ],
              "line_number": 4
            }
          },
          "function_name": {
            "kind": "token",
            "token": {
              "kind": "name",
              "text": "f1",
              "offset": 50,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 4
            }
          },
          "function_left_paren": {
            "kind": "token",
            "token": {
              "kind": "(",
              "text": "(",
              "offset": 52,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 4
            }
          },
          "function_parameter_list": {
            "kind": "list",
            "elements": [
              {
                "kind": "list_item",
                "list_item": {
                  "kind": "parameter_declaration",
                  "parameter_type": {
                    "kind": "closure_type_specifier",
                    "closure_outer_left_paren": {
                      "kind": "token",
                      "token": {
                        "kind": "(",
                        "text": "(",
                        "offset": 53,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 0,
                        "leading": [],
                        "trailing": [],
                        "line_number": 4
                      }
                    },
                    "closure_function_keyword": {
                      "kind": "token",
                      "token": {
                        "kind": "function",
                        "text": "function",
                        "offset": 54,
                        "leading_width": 0,
                        "width": 8,
                        "trailing_width": 0,
                        "leading": [],
                        "trailing": [],
                        "line_number": 4
                      }
                    },
                    "closure_inner_left_paren": {
                      "kind": "token",
                      "token": {
                        "kind": "(",
                        "text": "(",
                        "offset": 62,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 0,
                        "leading": [],
                        "trailing": [],
                        "line_number": 4
                      }
                    },
                    "closure_parameter_list": {
                      "kind": "list",
                      "elements": [
                        {
                          "kind": "list_item",
                          "list_item": {
                            "kind": "closure_parameter_type_specifier",
                            "closure_parameter_optional": {
                              "kind": "token",
                              "token": {
                                "kind": "optional",
                                "text": "optional",
                                "offset": 63,
                                "leading_width": 0,
                                "width": 8,
                                "trailing_width": 1,
                                "leading": [],
                                "trailing": [
                                  {
                                    "kind": "whitespace",
                                    "text": " ",
                                    "offset": 71,
                                    "width": 1
                                  }
                                ],
                                "line_number": 4
                              }
                            },
                            "closure_parameter_readonly": {
                              "kind": "token",
                              "token": {
                                "kind": "readonly",
                                "text": "readonly",
                                "offset": 72,
                                "leading_width": 0,
                                "width": 8,
                                "trailing_width": 1,
                                "leading": [],
                                "trailing": [
                                  {
                                    "kind": "whitespace",
                                    "text": " ",
                                    "offset": 80,
                                    "width": 1
                                  }
                                ],
                                "line_number": 4
                              }
                            },
                            "closure_parameter_type": {
                              "kind": "simple_type_specifier",
                              "simple_type_specifier": {
                                "kind": "token",
                                "token": {
                                  "kind": "bool",
                                  "text": "bool",
                                  "offset": 81,
                                  "leading_width": 0,
                                  "width": 4,
                                  "trailing_width": 0,
                                  "leading": [],
                                  "trailing": [],
                                  "line_number": 4
                                }
                              }
                            }
                          }
                        }
                      ]
                    },
                    "closure_inner_right_paren": {
                      "kind": "token",
                      "token": {
                        "kind": ")",
                        "text": ")",
                        "offset": 85,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 0,
                        "leading": [],
                        "trailing": [],
                        "line_number": 4
                      }
                    },
                    "closure_colon": {
                      "kind": "token",
                      "token": {
                        "kind": ":",
                        "text": ":",
                        "offset": 86,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 1,
                        "leading": [],
                        "trailing": [
                          {
                            "kind": "whitespace",
                            "text": " ",
                            "offset": 87,
                            "width": 1
                          }
                        ],
                        "line_number": 4
                      }
                    },
                    "closure_return_type": {
                      "kind": "simple_type_specifier",
                      "simple_type_specifier": {
                        "kind": "token",
                        "token": {
                          "kind": "void",
                          "text": "void",
                          "offset": 88,
                          "leading_width": 0,
                          "width": 4,
                          "trailing_width": 0,
                          "leading": [],
                          "trailing": [],
                          "line_number": 4
                        }
                      }
                    },
                    "closure_outer_right_paren": {
                      "kind": "token",
                      "token": {
                        "kind": ")",
                        "text": ")",
                        "offset": 92,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 1,
                        "leading": [],
                        "trailing": [
                          {
                            "kind": "whitespace",
                            "text": " ",
                            "offset": 93,
                            "width": 1
                          }
                        ],
                        "line_number": 4
                      }
                    }
                  },
                  "parameter_name": {
                    "kind": "token",
                    "token": {
                      "kind": "variable",
                      "text": "$_",
                      "offset": 94,
                      "leading_width": 0,
                      "width": 2,
                      "trailing_width": 0,
                      "leading": [],
                      "trailing": [],
                      "line_number": 4
                    }
                  }
                }
              }
            ]
          },
          "function_right_paren": {
            "kind": "token",
            "token": {
              "kind": ")",
              "text": ")",
              "offset": 96,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 4
            }
          },
          "function_colon": {
            "kind": "token",
            "token": {
              "kind": ":",
              "text": ":",
              "offset": 97,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 98,
                  "width": 1
                }
              ],
              "line_number": 4
            }
          },
          "function_type": {
            "kind": "simple_type_specifier",
            "simple_type_specifier": {
              "kind": "token",
              "token": {
                "kind": "void",
                "text": "void",
                "offset": 99,
                "leading_width": 0,
                "width": 4,
                "trailing_width": 1,
                "leading": [],
                "trailing": [
                  {
                    "kind": "whitespace",
                    "text": " ",
                    "offset": 103,
                    "width": 1
                  }
                ],
                "line_number": 4
              }
            }
          }
        },
        "function_body": {
          "kind": "compound_statement",
          "compound_left_brace": {
            "kind": "token",
            "token": {
              "kind": "{",
              "text": "{",
              "offset": 104,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 4
            }
          },
          "compound_right_brace": {
            "kind": "token",
            "token": {
              "kind": "}",
              "text": "}",
              "offset": 105,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 106,
                  "width": 1
                }
              ],
              "line_number": 4
            }
          }
        }
      },
      {
        "kind": "function_declaration",
        "function_declaration_header": {
          "kind": "function_declaration_header",
          "function_keyword": {
            "kind": "token",
            "token": {
              "kind": "function",
              "text": "function",
              "offset": 107,
              "leading_width": 0,
              "width": 8,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 115,
                  "width": 1
                }
              ],
              "line_number": 5
            }
          },
          "function_name": {
            "kind": "token",
            "token": {
              "kind": "name",
              "text": "f2",
              "offset": 116,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 5
            }
          },
          "function_left_paren": {
            "kind": "token",
            "token": {
              "kind": "(",
              "text": "(",
              "offset": 118,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 5
            }
          },
          "function_parameter_list": {
            "kind": "list",
            "elements": [
              {
                "kind": "list_item",
                "list_item": {
                  "kind": "parameter_declaration",
                  "parameter_type": {
                    "kind": "closure_type_specifier",
                    "closure_outer_left_paren": {
                      "kind": "token",
                      "token": {
                        "kind": "(",
                        "text": "(",
                        "offset": 119,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 0,
                        "leading": [],
                        "trailing": [],
                        "line_number": 5
                      }
                    },
                    "closure_function_keyword": {
                      "kind": "token",
                      "token": {
                        "kind": "function",
                        "text": "function",
                        "offset": 120,
                        "leading_width": 0,
                        "width": 8,
                        "trailing_width": 0,
                        "leading": [],
                        "trailing": [],
                        "line_number": 5
                      }
                    },
                    "closure_inner_left_paren": {
                      "kind": "token",
                      "token": {
                        "kind": "(",
                        "text": "(",
                        "offset": 128,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 0,
                        "leading": [],
                        "trailing": [],
                        "line_number": 5
                      }
                    },
                    "closure_parameter_list": {
                      "kind": "list",
                      "elements": [
                        {
                          "kind": "list_item",
                          "list_item": {
                            "kind": "closure_parameter_type_specifier",
                            "closure_parameter_optional": {
                              "kind": "token",
                              "token": {
                                "kind": "readonly",
                                "text": "readonly",
                                "offset": 129,
                                "leading_width": 0,
                                "width": 8,
                                "trailing_width": 1,
                                "leading": [],
                                "trailing": [
                                  {
                                    "kind": "whitespace",
                                    "text": " ",
                                    "offset": 137,
                                    "width": 1
                                  }
                                ],
                                "line_number": 5
                              }
                            },
                            "closure_parameter_call_convention": {
                              "kind": "token",
                              "token": {
                                "kind": "optional",
                                "text": "optional",
                                "offset": 138,
                                "leading_width": 0,
                                "width": 8,
                                "trailing_width": 1,
                                "leading": [],
                                "trailing": [
                                  {
                                    "kind": "whitespace",
                                    "text": " ",
                                    "offset": 146,
                                    "width": 1
                                  }
                                ],
                                "line_number": 5
                              }
                            },
                            "closure_parameter_type": {
                              "kind": "simple_type_specifier",
                              "simple_type_specifier": {
                                "kind": "token",
                                "token": {
                                  "kind": "bool",
                                  "text": "bool",
                                  "offset": 147,
                                  "leading_width": 0,
                                  "width": 4,
                                  "trailing_width": 0,
                                  "leading": [],
                                  "trailing": [],
                                  "line_number": 5
                                }
                              }
                            }
                          }
                        }
                      ]
                    },
                    "closure_inner_right_paren": {
                      "kind": "token",
                      "token": {
                        "kind": ")",
                        "text": ")",
                        "offset": 151,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 0,
                        "leading": [],
                        "trailing": [],
                        "line_number": 5
                      }
                    },
                    "closure_colon": {
                      "kind": "token",
                      "token": {
                        "kind": ":",
                        "text": ":",
                        "offset": 152,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 1,
                        "leading": [],
                        "trailing": [
                          {
                            "kind": "whitespace",
                            "text": " ",
                            "offset": 153,
                            "width": 1
                          }
                        ],
                        "line_number": 5
                      }
                    },
                    "closure_return_type": {
                      "kind": "simple_type_specifier",
                      "simple_type_specifier": {
                        "kind": "token",
                        "token": {
                          "kind": "void",
                          "text": "void",
                          "offset": 154,
                          "leading_width": 0,
                          "width": 4,
                          "trailing_width": 0,
                          "leading": [],
                          "trailing": [],
                          "line_number": 5
                        }
                      }
                    },
                    "closure_outer_right_paren": {
                      "kind": "token",
                      "token": {
                        "kind": ")",
                        "text": ")",
                        "offset": 158,
                        "leading_width": 0,
                        "width": 1,
                        "trailing_width": 1,
                        "leading": [],
                        "trailing": [
                          {
                            "kind": "whitespace",
                            "text": " ",
                            "offset": 159,
                            "width": 1
                          }
                        ],
                        "line_number": 5
                      }
                    }
                  },
                  "parameter_name": {
                    "kind": "token",
                    "token": {
                      "kind": "variable",
                      "text": "$_",
                      "offset": 160,
                      "leading_width": 0,
                      "width": 2,
                      "trailing_width": 0,
                      "leading": [],
                      "trailing": [],
                      "line_number": 5
                    }
                  }
                }
              }
            ]
          },
          "function_right_paren": {
            "kind": "token",
            "token": {
              "kind": ")",
              "text": ")",
              "offset": 162,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 5
            }
          },
          "function_colon": {
            "kind": "token",
            "token": {
              "kind": ":",
              "text": ":",
              "offset": 163,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 164,
                  "width": 1
                }
              ],
              "line_number": 5
            }
          },
          "function_type": {
            "kind": "simple_type_specifier",
            "simple_type_specifier": {
              "kind": "token",
              "token": {
                "kind": "void",
                "text": "void",
                "offset": 165,
                "leading_width": 0,
                "width": 4,
                "trailing_width": 1,
                "leading": [],
                "trailing": [
                  {
                    "kind": "whitespace",
                    "text": " ",
                    "offset": 169,
                    "width": 1
                  }
                ],
                "line_number": 5
              }
            }
          }
        },
        "function_body": {
          "kind": "compound_statement",
          "compound_left_brace": {
            "kind": "token",
            "token": {
              "kind": "{",
              "text": "{",
              "offset": 170,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 5
            }
          },
          "compound_right_brace": {
            "kind": "token",
            "token": {
              "kind": "}",
              "text": "}",
              "offset": 171,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 172,
                  "width": 1
                }
              ],
              "line_number": 5
            }
          }
        }
      },
      {
        "kind": "end_of_file",
        "end_of_file_token": {
          "kind": "token",
          "token": {
            "kind": "end_of_file",
            "text": "",
            "offset": 173,
            "leading_width": 0,
            "width": 0,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 6
          }
        }
      }
    ]
  }
}
