{
  "kind": "script",
  "script_declarations": {
    "kind": "list",
    "elements": [
      {
        "kind": "markup_section",
        "markup_suffix": {
          "kind": "markup_suffix",
          "markup_suffix_less_than_question": {
            "kind": "token",
            "token": {
              "kind": "<?",
              "text": "<?",
              "offset": 0,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 1
            }
          },
          "markup_suffix_name": {
            "kind": "token",
            "token": {
              "kind": "name",
              "text": "hh",
              "offset": 2,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 4,
                  "width": 1
                }
              ],
              "line_number": 1
            }
          }
        }
      },
      {
        "kind": "file_attribute_specification",
        "file_attribute_specification_left_double_angle": {
          "kind": "token",
          "token": {
            "kind": "<<",
            "text": "<<",
            "offset": 5,
            "leading_width": 1,
            "width": 2,
            "trailing_width": 0,
            "leading": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 5,
                "width": 1
              }
            ],
            "trailing": [],
            "line_number": 3
          }
        },
        "file_attribute_specification_keyword": {
          "kind": "token",
          "token": {
            "kind": "file",
            "text": "file",
            "offset": 8,
            "leading_width": 0,
            "width": 4,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 3
          }
        },
        "file_attribute_specification_colon": {
          "kind": "token",
          "token": {
            "kind": ":",
            "text": ":",
            "offset": 12,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 3
          }
        },
        "file_attribute_specification_attributes": {
          "kind": "list",
          "elements": [
            {
              "kind": "list_item",
              "list_item": {
                "kind": "constructor_call",
                "constructor_call_type": {
                  "kind": "simple_type_specifier",
                  "simple_type_specifier": {
                    "kind": "token",
                    "token": {
                      "kind": "name",
                      "text": "__EnableUnstableFeatures",
                      "offset": 13,
                      "leading_width": 0,
                      "width": 24,
                      "trailing_width": 0,
                      "leading": [],
                      "trailing": [],
                      "line_number": 3
                    }
                  }
                },
                "constructor_call_left_paren": {
                  "kind": "token",
                  "token": {
                    "kind": "(",
                    "text": "(",
                    "offset": 37,
                    "leading_width": 0,
                    "width": 1,
                    "trailing_width": 0,
                    "leading": [],
                    "trailing": [],
                    "line_number": 3
                  }
                },
                "constructor_call_argument_list": {
                  "kind": "list",
                  "elements": [
                    {
                      "kind": "list_item",
                      "list_item": {
                        "kind": "literal",
                        "literal_expression": {
                          "kind": "token",
                          "token": {
                            "kind": "single_quoted_string_literal",
                            "text": "'named_parameters'",
                            "offset": 38,
                            "leading_width": 0,
                            "width": 18,
                            "trailing_width": 0,
                            "leading": [],
                            "trailing": [],
                            "line_number": 3
                          }
                        }
                      }
                    }
                  ]
                },
                "constructor_call_right_paren": {
                  "kind": "token",
                  "token": {
                    "kind": ")",
                    "text": ")",
                    "offset": 56,
                    "leading_width": 0,
                    "width": 1,
                    "trailing_width": 0,
                    "leading": [],
                    "trailing": [],
                    "line_number": 3
                  }
                }
              }
            }
          ]
        },
        "file_attribute_specification_right_double_angle": {
          "kind": "token",
          "token": {
            "kind": ">>",
            "text": ">>",
            "offset": 57,
            "leading_width": 0,
            "width": 2,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 59,
                "width": 1
              }
            ],
            "line_number": 3
          }
        }
      },
      {
        "kind": "alias_declaration",
        "alias_keyword": {
          "kind": "token",
          "token": {
            "kind": "type",
            "text": "type",
            "offset": 60,
            "leading_width": 1,
            "width": 4,
            "trailing_width": 1,
            "leading": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 60,
                "width": 1
              }
            ],
            "trailing": [
              { "kind": "whitespace", "text": " ", "offset": 65, "width": 1 }
            ],
            "line_number": 5
          }
        },
        "alias_name": {
          "kind": "token",
          "token": {
            "kind": "name",
            "text": "OptionalNamed",
            "offset": 66,
            "leading_width": 0,
            "width": 13,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              { "kind": "whitespace", "text": " ", "offset": 79, "width": 1 }
            ],
            "line_number": 5
          }
        },
        "alias_equal": {
          "kind": "token",
          "token": {
            "kind": "=",
            "text": "=",
            "offset": 80,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              { "kind": "whitespace", "text": " ", "offset": 81, "width": 1 }
            ],
            "line_number": 5
          }
        },
        "alias_type": {
          "kind": "closure_type_specifier",
          "closure_outer_left_paren": {
            "kind": "token",
            "token": {
              "kind": "(",
              "text": "(",
              "offset": 82,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 5
            }
          },
          "closure_function_keyword": {
            "kind": "token",
            "token": {
              "kind": "function",
              "text": "function",
              "offset": 83,
              "leading_width": 0,
              "width": 8,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 5
            }
          },
          "closure_inner_left_paren": {
            "kind": "token",
            "token": {
              "kind": "(",
              "text": "(",
              "offset": 91,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 5
            }
          },
          "closure_parameter_list": {
            "kind": "list",
            "elements": [
              {
                "kind": "list_item",
                "list_item": {
                  "kind": "closure_parameter_type_specifier",
                  "closure_parameter_optional": {
                    "kind": "token",
                    "token": {
                      "kind": "optional",
                      "text": "optional",
                      "offset": 92,
                      "leading_width": 0,
                      "width": 8,
                      "trailing_width": 1,
                      "leading": [],
                      "trailing": [
                        {
                          "kind": "whitespace",
                          "text": " ",
                          "offset": 100,
                          "width": 1
                        }
                      ],
                      "line_number": 5
                    }
                  },
                  "closure_parameter_named": {
                    "kind": "token",
                    "token": {
                      "kind": "named",
                      "text": "named",
                      "offset": 101,
                      "leading_width": 0,
                      "width": 5,
                      "trailing_width": 1,
                      "leading": [],
                      "trailing": [
                        {
                          "kind": "whitespace",
                          "text": " ",
                          "offset": 106,
                          "width": 1
                        }
                      ],
                      "line_number": 5
                    }
                  },
                  "closure_parameter_type": {
                    "kind": "simple_type_specifier",
                    "simple_type_specifier": {
                      "kind": "token",
                      "token": {
                        "kind": "int",
                        "text": "int",
                        "offset": 107,
                        "leading_width": 0,
                        "width": 3,
                        "trailing_width": 1,
                        "leading": [],
                        "trailing": [
                          {
                            "kind": "whitespace",
                            "text": " ",
                            "offset": 110,
                            "width": 1
                          }
                        ],
                        "line_number": 5
                      }
                    }
                  },
                  "closure_parameter_name": {
                    "kind": "token",
                    "token": {
                      "kind": "variable",
                      "text": "$value",
                      "offset": 111,
                      "leading_width": 0,
                      "width": 6,
                      "trailing_width": 0,
                      "leading": [],
                      "trailing": [],
                      "line_number": 5
                    }
                  }
                }
              }
            ]
          },
          "closure_inner_right_paren": {
            "kind": "token",
            "token": {
              "kind": ")",
              "text": ")",
              "offset": 117,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 5
            }
          },
          "closure_colon": {
            "kind": "token",
            "token": {
              "kind": ":",
              "text": ":",
              "offset": 118,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 119,
                  "width": 1
                }
              ],
              "line_number": 5
            }
          },
          "closure_return_type": {
            "kind": "simple_type_specifier",
            "simple_type_specifier": {
              "kind": "token",
              "token": {
                "kind": "void",
                "text": "void",
                "offset": 120,
                "leading_width": 0,
                "width": 4,
                "trailing_width": 0,
                "leading": [],
                "trailing": [],
                "line_number": 5
              }
            }
          },
          "closure_outer_right_paren": {
            "kind": "token",
            "token": {
              "kind": ")",
              "text": ")",
              "offset": 124,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 5
            }
          }
        },
        "alias_semicolon": {
          "kind": "token",
          "token": {
            "kind": ";",
            "text": ";",
            "offset": 125,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 126,
                "width": 1
              }
            ],
            "line_number": 5
          }
        }
      },
      {
        "kind": "alias_declaration",
        "alias_keyword": {
          "kind": "token",
          "token": {
            "kind": "type",
            "text": "type",
            "offset": 127,
            "leading_width": 0,
            "width": 4,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "whitespace",
                "text": " ",
                "offset": 131,
                "width": 1
              }
            ],
            "line_number": 6
          }
        },
        "alias_name": {
          "kind": "token",
          "token": {
            "kind": "name",
            "text": "NamedOptional",
            "offset": 132,
            "leading_width": 0,
            "width": 13,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "whitespace",
                "text": " ",
                "offset": 145,
                "width": 1
              }
            ],
            "line_number": 6
          }
        },
        "alias_equal": {
          "kind": "token",
          "token": {
            "kind": "=",
            "text": "=",
            "offset": 146,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "whitespace",
                "text": " ",
                "offset": 147,
                "width": 1
              }
            ],
            "line_number": 6
          }
        },
        "alias_type": {
          "kind": "closure_type_specifier",
          "closure_outer_left_paren": {
            "kind": "token",
            "token": {
              "kind": "(",
              "text": "(",
              "offset": 148,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 6
            }
          },
          "closure_function_keyword": {
            "kind": "token",
            "token": {
              "kind": "function",
              "text": "function",
              "offset": 149,
              "leading_width": 0,
              "width": 8,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 6
            }
          },
          "closure_inner_left_paren": {
            "kind": "token",
            "token": {
              "kind": "(",
              "text": "(",
              "offset": 157,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 6
            }
          },
          "closure_parameter_list": {
            "kind": "list",
            "elements": [
              {
                "kind": "list_item",
                "list_item": {
                  "kind": "closure_parameter_type_specifier",
                  "closure_parameter_optional": {
                    "kind": "token",
                    "token": {
                      "kind": "named",
                      "text": "named",
                      "offset": 158,
                      "leading_width": 0,
                      "width": 5,
                      "trailing_width": 1,
                      "leading": [],
                      "trailing": [
                        {
                          "kind": "whitespace",
                          "text": " ",
                          "offset": 163,
                          "width": 1
                        }
                      ],
                      "line_number": 6
                    }
                  },
                  "closure_parameter_call_convention": {
                    "kind": "token",
                    "token": {
                      "kind": "optional",
                      "text": "optional",
                      "offset": 164,
                      "leading_width": 0,
                      "width": 8,
                      "trailing_width": 1,
                      "leading": [],
                      "trailing": [
                        {
                          "kind": "whitespace",
                          "text": " ",
                          "offset": 172,
                          "width": 1
                        }
                      ],
                      "line_number": 6
                    }
                  },
                  "closure_parameter_type": {
                    "kind": "simple_type_specifier",
                    "simple_type_specifier": {
                      "kind": "token",
                      "token": {
                        "kind": "int",
                        "text": "int",
                        "offset": 173,
                        "leading_width": 0,
                        "width": 3,
                        "trailing_width": 1,
                        "leading": [],
                        "trailing": [
                          {
                            "kind": "whitespace",
                            "text": " ",
                            "offset": 176,
                            "width": 1
                          }
                        ],
                        "line_number": 6
                      }
                    }
                  },
                  "closure_parameter_name": {
                    "kind": "token",
                    "token": {
                      "kind": "variable",
                      "text": "$value",
                      "offset": 177,
                      "leading_width": 0,
                      "width": 6,
                      "trailing_width": 0,
                      "leading": [],
                      "trailing": [],
                      "line_number": 6
                    }
                  }
                }
              }
            ]
          },
          "closure_inner_right_paren": {
            "kind": "token",
            "token": {
              "kind": ")",
              "text": ")",
              "offset": 183,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 6
            }
          },
          "closure_colon": {
            "kind": "token",
            "token": {
              "kind": ":",
              "text": ":",
              "offset": 184,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 185,
                  "width": 1
                }
              ],
              "line_number": 6
            }
          },
          "closure_return_type": {
            "kind": "simple_type_specifier",
            "simple_type_specifier": {
              "kind": "token",
              "token": {
                "kind": "void",
                "text": "void",
                "offset": 186,
                "leading_width": 0,
                "width": 4,
                "trailing_width": 0,
                "leading": [],
                "trailing": [],
                "line_number": 6
              }
            }
          },
          "closure_outer_right_paren": {
            "kind": "token",
            "token": {
              "kind": ")",
              "text": ")",
              "offset": 190,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 6
            }
          }
        },
        "alias_semicolon": {
          "kind": "token",
          "token": {
            "kind": ";",
            "text": ";",
            "offset": 191,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 192,
                "width": 1
              }
            ],
            "line_number": 6
          }
        }
      },
      {
        "kind": "end_of_file",
        "end_of_file_token": {
          "kind": "token",
          "token": {
            "kind": "end_of_file",
            "text": "",
            "offset": 193,
            "leading_width": 32,
            "width": 0,
            "trailing_width": 0,
            "leading": [
              {
                "kind": "single_line_comment",
                "text": "// Optional must precede named.",
                "offset": 193,
                "width": 31
              },
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 224,
                "width": 1
              }
            ],
            "trailing": [],
            "line_number": 8
          }
        }
      }
    ]
  }
}
