{
  "kind": "script",
  "script_declarations": {
    "kind": "list",
    "elements": [
      {
        "kind": "markup_section",
        "markup_suffix": {
          "kind": "markup_suffix",
          "markup_suffix_less_than_question": {
            "kind": "token",
            "token": {
              "kind": "<?",
              "text": "<?",
              "offset": 0,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 1
            }
          },
          "markup_suffix_name": {
            "kind": "token",
            "token": {
              "kind": "name",
              "text": "hh",
              "offset": 2,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 4,
                  "width": 1
                }
              ],
              "line_number": 1
            }
          }
        }
      },
      {
        "kind": "file_attribute_specification",
        "file_attribute_specification_left_double_angle": {
          "kind": "token",
          "token": {
            "kind": "<<",
            "text": "<<",
            "offset": 5,
            "leading_width": 63,
            "width": 2,
            "trailing_width": 0,
            "leading": [
              {
                "kind": "single_line_comment",
                "text": "// Named and inout modifiers are incompatible in either order.",
                "offset": 5,
                "width": 62
              },
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 67,
                "width": 1
              }
            ],
            "trailing": [],
            "line_number": 3
          }
        },
        "file_attribute_specification_keyword": {
          "kind": "token",
          "token": {
            "kind": "file",
            "text": "file",
            "offset": 70,
            "leading_width": 0,
            "width": 4,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 3
          }
        },
        "file_attribute_specification_colon": {
          "kind": "token",
          "token": {
            "kind": ":",
            "text": ":",
            "offset": 74,
            "leading_width": 0,
            "width": 1,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 3
          }
        },
        "file_attribute_specification_attributes": {
          "kind": "list",
          "elements": [
            {
              "kind": "list_item",
              "list_item": {
                "kind": "constructor_call",
                "constructor_call_type": {
                  "kind": "simple_type_specifier",
                  "simple_type_specifier": {
                    "kind": "token",
                    "token": {
                      "kind": "name",
                      "text": "__EnableUnstableFeatures",
                      "offset": 75,
                      "leading_width": 0,
                      "width": 24,
                      "trailing_width": 0,
                      "leading": [],
                      "trailing": [],
                      "line_number": 3
                    }
                  }
                },
                "constructor_call_left_paren": {
                  "kind": "token",
                  "token": {
                    "kind": "(",
                    "text": "(",
                    "offset": 99,
                    "leading_width": 0,
                    "width": 1,
                    "trailing_width": 0,
                    "leading": [],
                    "trailing": [],
                    "line_number": 3
                  }
                },
                "constructor_call_argument_list": {
                  "kind": "list",
                  "elements": [
                    {
                      "kind": "list_item",
                      "list_item": {
                        "kind": "literal",
                        "literal_expression": {
                          "kind": "token",
                          "token": {
                            "kind": "single_quoted_string_literal",
                            "text": "'named_parameters'",
                            "offset": 100,
                            "leading_width": 0,
                            "width": 18,
                            "trailing_width": 0,
                            "leading": [],
                            "trailing": [],
                            "line_number": 3
                          }
                        }
                      }
                    }
                  ]
                },
                "constructor_call_right_paren": {
                  "kind": "token",
                  "token": {
                    "kind": ")",
                    "text": ")",
                    "offset": 118,
                    "leading_width": 0,
                    "width": 1,
                    "trailing_width": 0,
                    "leading": [],
                    "trailing": [],
                    "line_number": 3
                  }
                }
              }
            }
          ]
        },
        "file_attribute_specification_right_double_angle": {
          "kind": "token",
          "token": {
            "kind": ">>",
            "text": ">>",
            "offset": 119,
            "leading_width": 0,
            "width": 2,
            "trailing_width": 1,
            "leading": [],
            "trailing": [
              {
                "kind": "end_of_line",
                "text": "\n",
                "offset": 121,
                "width": 1
              }
            ],
            "line_number": 3
          }
        }
      },
      {
        "kind": "function_declaration",
        "function_declaration_header": {
          "kind": "function_declaration_header",
          "function_keyword": {
            "kind": "token",
            "token": {
              "kind": "function",
              "text": "function",
              "offset": 122,
              "leading_width": 1,
              "width": 8,
              "trailing_width": 1,
              "leading": [
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 122,
                  "width": 1
                }
              ],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 131,
                  "width": 1
                }
              ],
              "line_number": 5
            }
          },
          "function_name": {
            "kind": "token",
            "token": {
              "kind": "name",
              "text": "f1",
              "offset": 132,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 5
            }
          },
          "function_left_paren": {
            "kind": "token",
            "token": {
              "kind": "(",
              "text": "(",
              "offset": 134,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 5
            }
          },
          "function_parameter_list": {
            "kind": "list",
            "elements": [
              {
                "kind": "list_item",
                "list_item": {
                  "kind": "parameter_declaration",
                  "parameter_optional": {
                    "kind": "token",
                    "token": {
                      "kind": "named",
                      "text": "named",
                      "offset": 135,
                      "leading_width": 0,
                      "width": 5,
                      "trailing_width": 1,
                      "leading": [],
                      "trailing": [
                        {
                          "kind": "whitespace",
                          "text": " ",
                          "offset": 140,
                          "width": 1
                        }
                      ],
                      "line_number": 5
                    }
                  },
                  "parameter_call_convention": {
                    "kind": "token",
                    "token": {
                      "kind": "inout",
                      "text": "inout",
                      "offset": 141,
                      "leading_width": 0,
                      "width": 5,
                      "trailing_width": 1,
                      "leading": [],
                      "trailing": [
                        {
                          "kind": "whitespace",
                          "text": " ",
                          "offset": 146,
                          "width": 1
                        }
                      ],
                      "line_number": 5
                    }
                  },
                  "parameter_type": {
                    "kind": "simple_type_specifier",
                    "simple_type_specifier": {
                      "kind": "token",
                      "token": {
                        "kind": "bool",
                        "text": "bool",
                        "offset": 147,
                        "leading_width": 0,
                        "width": 4,
                        "trailing_width": 1,
                        "leading": [],
                        "trailing": [
                          {
                            "kind": "whitespace",
                            "text": " ",
                            "offset": 151,
                            "width": 1
                          }
                        ],
                        "line_number": 5
                      }
                    }
                  },
                  "parameter_name": {
                    "kind": "token",
                    "token": {
                      "kind": "variable",
                      "text": "$x",
                      "offset": 152,
                      "leading_width": 0,
                      "width": 2,
                      "trailing_width": 0,
                      "leading": [],
                      "trailing": [],
                      "line_number": 5
                    }
                  }
                }
              }
            ]
          },
          "function_right_paren": {
            "kind": "token",
            "token": {
              "kind": ")",
              "text": ")",
              "offset": 154,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 5
            }
          },
          "function_colon": {
            "kind": "token",
            "token": {
              "kind": ":",
              "text": ":",
              "offset": 155,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 156,
                  "width": 1
                }
              ],
              "line_number": 5
            }
          },
          "function_type": {
            "kind": "simple_type_specifier",
            "simple_type_specifier": {
              "kind": "token",
              "token": {
                "kind": "void",
                "text": "void",
                "offset": 157,
                "leading_width": 0,
                "width": 4,
                "trailing_width": 1,
                "leading": [],
                "trailing": [
                  {
                    "kind": "whitespace",
                    "text": " ",
                    "offset": 161,
                    "width": 1
                  }
                ],
                "line_number": 5
              }
            }
          }
        },
        "function_body": {
          "kind": "compound_statement",
          "compound_left_brace": {
            "kind": "token",
            "token": {
              "kind": "{",
              "text": "{",
              "offset": 162,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 5
            }
          },
          "compound_right_brace": {
            "kind": "token",
            "token": {
              "kind": "}",
              "text": "}",
              "offset": 163,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 164,
                  "width": 1
                }
              ],
              "line_number": 5
            }
          }
        }
      },
      {
        "kind": "function_declaration",
        "function_declaration_header": {
          "kind": "function_declaration_header",
          "function_keyword": {
            "kind": "token",
            "token": {
              "kind": "function",
              "text": "function",
              "offset": 165,
              "leading_width": 0,
              "width": 8,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 173,
                  "width": 1
                }
              ],
              "line_number": 6
            }
          },
          "function_name": {
            "kind": "token",
            "token": {
              "kind": "name",
              "text": "f2",
              "offset": 174,
              "leading_width": 0,
              "width": 2,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 6
            }
          },
          "function_left_paren": {
            "kind": "token",
            "token": {
              "kind": "(",
              "text": "(",
              "offset": 176,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 6
            }
          },
          "function_parameter_list": {
            "kind": "list",
            "elements": [
              {
                "kind": "list_item",
                "list_item": {
                  "kind": "parameter_declaration",
                  "parameter_call_convention": {
                    "kind": "token",
                    "token": {
                      "kind": "inout",
                      "text": "inout",
                      "offset": 177,
                      "leading_width": 0,
                      "width": 5,
                      "trailing_width": 1,
                      "leading": [],
                      "trailing": [
                        {
                          "kind": "whitespace",
                          "text": " ",
                          "offset": 182,
                          "width": 1
                        }
                      ],
                      "line_number": 6
                    }
                  },
                  "parameter_named": {
                    "kind": "token",
                    "token": {
                      "kind": "named",
                      "text": "named",
                      "offset": 183,
                      "leading_width": 0,
                      "width": 5,
                      "trailing_width": 1,
                      "leading": [],
                      "trailing": [
                        {
                          "kind": "whitespace",
                          "text": " ",
                          "offset": 188,
                          "width": 1
                        }
                      ],
                      "line_number": 6
                    }
                  },
                  "parameter_type": {
                    "kind": "simple_type_specifier",
                    "simple_type_specifier": {
                      "kind": "token",
                      "token": {
                        "kind": "bool",
                        "text": "bool",
                        "offset": 189,
                        "leading_width": 0,
                        "width": 4,
                        "trailing_width": 1,
                        "leading": [],
                        "trailing": [
                          {
                            "kind": "whitespace",
                            "text": " ",
                            "offset": 193,
                            "width": 1
                          }
                        ],
                        "line_number": 6
                      }
                    }
                  },
                  "parameter_name": {
                    "kind": "token",
                    "token": {
                      "kind": "variable",
                      "text": "$y",
                      "offset": 194,
                      "leading_width": 0,
                      "width": 2,
                      "trailing_width": 0,
                      "leading": [],
                      "trailing": [],
                      "line_number": 6
                    }
                  }
                }
              }
            ]
          },
          "function_right_paren": {
            "kind": "token",
            "token": {
              "kind": ")",
              "text": ")",
              "offset": 196,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 6
            }
          },
          "function_colon": {
            "kind": "token",
            "token": {
              "kind": ":",
              "text": ":",
              "offset": 197,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "whitespace",
                  "text": " ",
                  "offset": 198,
                  "width": 1
                }
              ],
              "line_number": 6
            }
          },
          "function_type": {
            "kind": "simple_type_specifier",
            "simple_type_specifier": {
              "kind": "token",
              "token": {
                "kind": "void",
                "text": "void",
                "offset": 199,
                "leading_width": 0,
                "width": 4,
                "trailing_width": 1,
                "leading": [],
                "trailing": [
                  {
                    "kind": "whitespace",
                    "text": " ",
                    "offset": 203,
                    "width": 1
                  }
                ],
                "line_number": 6
              }
            }
          }
        },
        "function_body": {
          "kind": "compound_statement",
          "compound_left_brace": {
            "kind": "token",
            "token": {
              "kind": "{",
              "text": "{",
              "offset": 204,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 0,
              "leading": [],
              "trailing": [],
              "line_number": 6
            }
          },
          "compound_right_brace": {
            "kind": "token",
            "token": {
              "kind": "}",
              "text": "}",
              "offset": 205,
              "leading_width": 0,
              "width": 1,
              "trailing_width": 1,
              "leading": [],
              "trailing": [
                {
                  "kind": "end_of_line",
                  "text": "\n",
                  "offset": 206,
                  "width": 1
                }
              ],
              "line_number": 6
            }
          }
        }
      },
      {
        "kind": "end_of_file",
        "end_of_file_token": {
          "kind": "token",
          "token": {
            "kind": "end_of_file",
            "text": "",
            "offset": 207,
            "leading_width": 0,
            "width": 0,
            "trailing_width": 0,
            "leading": [],
            "trailing": [],
            "line_number": 7
          }
        }
      }
    ]
  }
}
