WARN: File "errors_1.php", line 3, characters 22-42:
An `abstract final` class cannot be `__ConsistentConstruct`. `AbstractFinalCCDirect` is `__ConsistentConstruct`. (Warn[12037])
WARN: File "errors_1.php", line 7, characters 22-43:
An `abstract final` class cannot be `__ConsistentConstruct`. Class `AbstractFinalChildOfCC` inherits `__ConsistentConstruct` from `AbstractCCRoot`. (Warn[12037])
WARN: File "errors_1.php", line 12, characters 22-44:
An `abstract final` class cannot be `__ConsistentConstruct`. Class `AbstractFinalGrandchild` inherits `__ConsistentConstruct` from `MiddleClass`. (Warn[12037])
