ERROR: File "function_ref.php", line 50, characters 17-18:
Invalid argument (Typing[4110])
  File "function_ref.php", line 38, characters 37-42:
  Expected `string`
  File "function_ref.php", line 42, characters 37-44:
  But got `arraykey`
ERROR: File "function_ref.php", line 50, characters 17-18:
Invalid argument (Typing[4110])
  File "function_ref.php", line 42, characters 48-55:
  Expected `arraykey`
  File "function_ref.php", line 38, characters 46-50:
  But got `mixed`
ERROR: File "function_ref.php", line 67, characters 17-19:
Invalid argument (Typing[4110])
  File "function_ref.php", line 18, characters 28-35:
  Expected `arraykey`
  File "function_ref.php", line 38, characters 46-50:
  But got `mixed`
ERROR: File "function_ref.php", line 67, characters 17-19:
Invalid argument (Typing[4110])
  File "function_ref.php", line 38, characters 37-42:
  Expected `string`
  File "function_ref.php", line 18, characters 14-21:
  But got `arraykey`
ERROR: File "function_ref.php", line 74, characters 17-19:
Invalid argument (Typing[4110])
  File "function_ref.php", line 4, characters 52-59:
  Expected `arraykey`
  File "function_ref.php", line 38, characters 46-50:
  But got `mixed`
ERROR: File "function_ref.php", line 74, characters 17-19:
Invalid argument (Typing[4110])
  File "function_ref.php", line 38, characters 37-42:
  Expected `string`
  File "function_ref.php", line 4, characters 38-45:
  But got `arraykey`
ERROR: File "function_ref.php", line 84, characters 16-19:
Invalid argument (Typing[4110])
  File "function_ref.php", line 30, characters 3-57:
  Expected `HH\FunctionRef<(readonly function(arraykey): arraykey)>`
  File "function_ref.php", line 81, characters 10-39:
  But got `(function(arraykey $x): arraykey)`
ERROR: File "function_ref.php", line 89, characters 16-18:
Invalid argument (Typing[4110])
  File "function_ref.php", line 21, characters 22-22:
  Expected `T#1` which corresponds to the rank-2 type parameter `T` in the polymorphic function
  File "function_ref.php", line 30, characters 48-55:
  But got `arraykey`
ERROR: File "function_ref.php", line 89, characters 16-18:
Invalid argument (Typing[4110])
  File "function_ref.php", line 30, characters 37-44:
  Expected `arraykey`
  File "function_ref.php", line 21, characters 22-22:
  But got `T#1` which corresponds to the rank-2 type parameter `T` in the polymorphic function
ERROR: File "function_ref.php", line 89, characters 16-18:
Invalid argument (Typing[4110])
  File "function_ref.php", line 30, characters 37-44:
  Expected `arraykey`
  File "function_ref.php", line 21, characters 22-22:
  But got `mixed` where `T#1` corresponds to the rank-2 type parameter `T` in the polymorphic function
ERROR: File "function_ref.php", line 94, characters 16-19:
Invalid argument (Typing[4110])
  File "function_ref.php", line 10, characters 46-46:
  Expected `T#1` which corresponds to the rank-2 type parameter `T` in the polymorphic function
  File "function_ref.php", line 30, characters 48-55:
  But got `arraykey`
ERROR: File "function_ref.php", line 94, characters 16-19:
Invalid argument (Typing[4110])
  File "function_ref.php", line 30, characters 37-44:
  Expected `arraykey`
  File "function_ref.php", line 10, characters 46-46:
  But got `T#1` which corresponds to the rank-2 type parameter `T` in the polymorphic function
ERROR: File "function_ref.php", line 94, characters 16-19:
Invalid argument (Typing[4110])
  File "function_ref.php", line 30, characters 37-44:
  Expected `arraykey`
  File "function_ref.php", line 10, characters 46-46:
  But got `mixed` where `T#1` corresponds to the rank-2 type parameter `T` in the polymorphic function
ERROR: File "function_ref.php", line 99, characters 17-19:
Invalid argument (Typing[4110])
  File "function_ref.php", line 13, characters 32-32:
  Expected `T#1` which corresponds to the rank-2 type parameter `T` in the polymorphic function
  File "function_ref.php", line 34, characters 51-58:
  But got `arraykey`
ERROR: File "function_ref.php", line 99, characters 17-19:
Invalid argument (Typing[4110])
  File "function_ref.php", line 34, characters 40-47:
  Expected `arraykey`
  File "function_ref.php", line 13, characters 32-32:
  But got `T#1` which corresponds to the rank-2 type parameter `T` in the polymorphic function
ERROR: File "function_ref.php", line 99, characters 17-19:
Invalid argument (Typing[4110])
  File "function_ref.php", line 34, characters 40-47:
  Expected `arraykey`
  File "function_ref.php", line 13, characters 32-32:
  But got `mixed` where `T#1` corresponds to the rank-2 type parameter `T` in the polymorphic function
ERROR: File "function_ref.php", line 102, characters 13-32:
Invalid argument (Typing[4411])
  File "function_ref.php", line 102, characters 13-32:
  Function readonly mismatch
  File "function_ref.php", line 102, characters 13-32:
  This function is not marked readonly
  File "function_ref.php", line 18, characters 10-12:
  This function is marked readonly
ERROR: File "function_ref.php", line 103, characters 19-38:
Invalid argument (Typing[4411])
  File "function_ref.php", line 103, characters 19-38:
  Function readonly mismatch
  File "function_ref.php", line 103, characters 19-38:
  This function is not marked readonly
  File "function_ref.php", line 18, characters 10-12:
  This function is marked readonly
