Code actions available:
------------------------------------------
Add __NeedsConcrete attribute (CodeActionKind: "quickfix") SELECTED
Devmate Quick Fix - Dangerous access of abstract member `A::m2`; it may be abstract and `static` might refer to an abstract class here. Consider adding the `__NeedsConcrete` attribute to the containing method. (CodeActionKind: "quickfix")
Devmate Agent Fix - Dangerous access of abstract member `A::m2`; it may be abstract and `static` might refer to an abstract class here. Consider adding the `__NeedsConcrete` attribute to the containing method. (CodeActionKind: "quickfix")

JSON for selected code action:
------------------------------------------
{
  "title": "Add __NeedsConcrete attribute",
  "kind": "quickfix",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 2 },
            "end": { "line": 3, "character": 2 }
          },
          "newText": "<<__NeedsConcrete>>\n  "
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

abstract class A {
  <<__NeedsConcrete>>
  private static function m1(): void {
    static::m2();
    //       ^ at-caret
  }

  public static abstract function m2(): void;
}

