FoldedClass {
    name: "\\:quux",
    kind: Cclass(
        Concrete,
    ),
    is_xhp: true,
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: class<this>,
            origin: "\\:quux",
            refs: [],
            value: CVAbsent,
        },
    },
}
FoldedClass {
    name: "\\:bar",
    kind: Cclass(
        Concrete,
    ),
    is_xhp: true,
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: class<this>,
            origin: "\\:bar",
            refs: [],
            value: CVAbsent,
        },
    },
    xhp_attr_deps: {
        "\\:quux",
    },
}
FoldedClass {
    name: "\\:foo",
    kind: Cclass(
        Concrete,
    ),
    is_xhp: true,
    consts: {
        "class": ClassConst {
            is_synthesized: true,
            kind: CCConcrete,
            pos: NPos,
            ty: class<this>,
            origin: "\\:foo",
            refs: [],
            value: CVAbsent,
        },
    },
    xhp_attr_deps: {
        "\\:bar",
        "\\:quux",
    },
}
