WARN: File "nullsafe-any.php", line 16, characters 11-13:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
WARN: File "nullsafe-any.php", line 16, characters 11-25:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
WARN: File "nullsafe-any.php", line 16, characters 17-25:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
WARN: File "nullsafe-any.php", line 17, characters 9-17:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
WARN: File "nullsafe-any.php", line 17, characters 15-17:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
ERROR: File "nullsafe-any.php", line 18, characters 8-9:
String concatenation can only be performed on string and int arguments (Typing[4110])
  File "nullsafe-any.php", line 18, characters 8-9:
  Expected `string` or `int`
  File "nullsafe-any.php", line 15, characters 8-18:
  But got `?int` (use of `?->` operator)
