WARN: File "lambda_params_5_plus.php", line 19, characters 24-27:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
ERROR: File "lambda_params_5_plus.php", line 16, characters 30-42:
No type constant `TDoesNotExist` in `WithConcreteTypeconst` (Typing[4090])
  File "lambda_params_5_plus.php", line 7, characters 13-33:
  Declaration of `WithConcreteTypeconst` is here
