ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_inout.php", line 5, characters 30-34:
Duplicate parameter modifier `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_named.php", line 6, characters 30-34:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_named_optional.php", line 5, characters 24-50:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_named_optional.php", line 5, characters 30-34:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_named_optional_readonly.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_named_optional_readonly.php", line 5, characters 30-34:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_named_optional_readonly.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_named_readonly.php", line 5, characters 30-34:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_named_readonly.php", line 5, characters 49-50:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_named_readonly_optional.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_named_readonly_optional.php", line 5, characters 30-34:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_named_readonly_optional.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_optional.php", line 5, characters 24-44:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_optional_named.php", line 5, characters 24-50:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_optional_named.php", line 5, characters 39-43:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_optional_named_readonly.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_optional_named_readonly.php", line 5, characters 39-43:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_optional_named_readonly.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_optional_readonly.php", line 5, characters 24-53:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_optional_readonly.php", line 5, characters 52-53:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_optional_readonly_named.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_optional_readonly_named.php", line 5, characters 48-52:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_optional_readonly_named.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_readonly.php", line 5, characters 43-44:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_readonly_named.php", line 5, characters 39-43:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_readonly_named.php", line 5, characters 49-50:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_readonly_named_optional.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_readonly_named_optional.php", line 5, characters 39-43:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_readonly_named_optional.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_readonly_optional.php", line 5, characters 24-53:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_readonly_optional.php", line 5, characters 52-53:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_readonly_optional_named.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_readonly_optional_named.php", line 5, characters 48-52:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_inout_readonly_optional_named.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_inout.php", line 5, characters 24-28:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_inout_optional.php", line 5, characters 24-28:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_inout_optional.php", line 5, characters 24-50:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_inout_optional_readonly.php", line 5, characters 24-28:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_inout_optional_readonly.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_inout_optional_readonly.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_inout_readonly.php", line 5, characters 24-28:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_inout_readonly.php", line 5, characters 49-50:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_inout_readonly_optional.php", line 5, characters 24-28:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_inout_readonly_optional.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_inout_readonly_optional.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_named.php", line 5, characters 30-34:
Duplicate parameter modifier `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_optional.php", line 5, characters 30-37:
Invalid parameter modifier order. The correct order is `optional named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_optional_inout.php", line 5, characters 24-28:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_optional_inout.php", line 5, characters 24-50:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_optional_inout_readonly.php", line 5, characters 24-28:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_optional_inout_readonly.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_optional_inout_readonly.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_optional_readonly.php", line 5, characters 30-37:
Invalid parameter modifier order. The correct order is `optional named readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_optional_readonly_inout.php", line 5, characters 24-28:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_optional_readonly_inout.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_optional_readonly_inout.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_readonly_inout.php", line 5, characters 24-28:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_readonly_inout.php", line 5, characters 49-50:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_readonly_inout_optional.php", line 5, characters 24-28:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_readonly_inout_optional.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_readonly_inout_optional.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_readonly_optional.php", line 5, characters 39-46:
Invalid parameter modifier order. The correct order is `optional named readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_readonly_optional_inout.php", line 5, characters 24-28:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_readonly_optional_inout.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_named_readonly_optional_inout.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_inout.php", line 5, characters 24-44:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_inout_named.php", line 5, characters 24-50:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_inout_named.php", line 5, characters 39-43:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_inout_named_readonly.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_inout_named_readonly.php", line 5, characters 39-43:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_inout_named_readonly.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_inout_readonly.php", line 5, characters 24-53:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_inout_readonly.php", line 5, characters 52-53:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_inout_readonly_named.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_inout_readonly_named.php", line 5, characters 48-52:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_inout_readonly_named.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_named_inout.php", line 5, characters 24-50:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_named_inout.php", line 5, characters 33-37:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_named_inout_readonly.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_named_inout_readonly.php", line 5, characters 33-37:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_named_inout_readonly.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_named_readonly_inout.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_named_readonly_inout.php", line 5, characters 33-37:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_named_readonly_inout.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_optional.php", line 5, characters 33-40:
Duplicate parameter modifier `optional`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_readonly_inout.php", line 5, characters 24-53:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_readonly_inout.php", line 5, characters 52-53:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_readonly_inout_named.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_readonly_inout_named.php", line 5, characters 48-52:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_readonly_inout_named.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_readonly_named.php", line 5, characters 42-46:
Invalid parameter modifier order. The correct order is `optional named readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_readonly_named_inout.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_readonly_named_inout.php", line 5, characters 42-46:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_optional_readonly_named_inout.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_inout.php", line 5, characters 43-44:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_inout_named.php", line 5, characters 39-43:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_inout_named.php", line 5, characters 49-50:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_inout_named_optional.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_inout_named_optional.php", line 5, characters 39-43:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_inout_named_optional.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_inout_optional.php", line 5, characters 24-53:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_inout_optional.php", line 5, characters 52-53:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_inout_optional_named.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_inout_optional_named.php", line 5, characters 48-52:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_inout_optional_named.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_named.php", line 5, characters 33-37:
Invalid parameter modifier order. The correct order is `named readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_named_inout.php", line 5, characters 33-37:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_named_inout.php", line 5, characters 49-50:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_named_inout_optional.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_named_inout_optional.php", line 5, characters 33-37:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_named_inout_optional.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_named_optional.php", line 5, characters 33-37:
Invalid parameter modifier order. The correct order is `optional named readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_named_optional_inout.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_named_optional_inout.php", line 5, characters 33-37:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_named_optional_inout.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_optional.php", line 5, characters 33-40:
Invalid parameter modifier order. The correct order is `optional readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_optional_inout.php", line 5, characters 24-53:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_optional_inout.php", line 5, characters 52-53:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_optional_inout_named.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_optional_inout_named.php", line 5, characters 48-52:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_optional_inout_named.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_optional_named.php", line 5, characters 33-40:
Invalid parameter modifier order. The correct order is `optional named readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_optional_named_inout.php", line 5, characters 24-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_optional_named_inout.php", line 5, characters 42-46:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_optional_named_inout.php", line 5, characters 58-59:
A parameter cannot be both `inout` and `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--abstract_method_readonly_readonly.php", line 5, characters 33-40:
Duplicate parameter modifier `readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_inout.php", line 4, characters 47-51:
Duplicate parameter modifier `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_named.php", line 4, characters 47-51:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_named_optional.php", line 4, characters 49-53:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_named_optional.php", line 4, characters 55-59:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_named_optional_readonly.php", line 4, characters 57-61:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_named_optional_readonly.php", line 4, characters 63-67:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_named_readonly.php", line 4, characters 55-59:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_named_readonly_optional.php", line 4, characters 57-61:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_named_readonly_optional.php", line 4, characters 63-67:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_optional.php", line 4, characters 44-48:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_optional_named.php", line 4, characters 49-53:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_optional_named.php", line 4, characters 64-68:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_optional_named_readonly.php", line 4, characters 57-61:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_optional_named_readonly.php", line 4, characters 72-76:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_optional_readonly.php", line 4, characters 52-56:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_optional_readonly_named.php", line 4, characters 57-61:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_optional_readonly_named.php", line 4, characters 81-85:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_readonly_named.php", line 4, characters 64-68:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_readonly_named_optional.php", line 4, characters 57-61:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_readonly_named_optional.php", line 4, characters 72-76:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_readonly_optional.php", line 4, characters 52-56:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_readonly_optional_named.php", line 4, characters 57-61:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_inout_readonly_optional_named.php", line 4, characters 81-85:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_inout.php", line 4, characters 41-45:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_inout_optional.php", line 4, characters 49-53:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_inout_optional.php", line 4, characters 55-59:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_inout_optional_readonly.php", line 4, characters 57-61:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_inout_optional_readonly.php", line 4, characters 63-67:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_inout_readonly.php", line 4, characters 49-53:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_inout_readonly_optional.php", line 4, characters 57-61:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_inout_readonly_optional.php", line 4, characters 63-67:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_named.php", line 4, characters 47-51:
Duplicate parameter modifier `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_optional.php", line 4, characters 50-57:
Invalid parameter modifier order. The correct order is `optional named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_optional_inout.php", line 4, characters 49-53:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_optional_inout.php", line 4, characters 64-68:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_optional_inout_readonly.php", line 4, characters 57-61:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_optional_inout_readonly.php", line 4, characters 72-76:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_optional_readonly.php", line 4, characters 58-65:
Invalid parameter modifier order. The correct order is `optional named readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_optional_readonly_inout.php", line 4, characters 57-61:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_optional_readonly_inout.php", line 4, characters 81-85:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_readonly_inout.php", line 4, characters 49-53:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_readonly_inout_optional.php", line 4, characters 57-61:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_readonly_inout_optional.php", line 4, characters 72-76:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_readonly_optional.php", line 4, characters 67-74:
Invalid parameter modifier order. The correct order is `optional named readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_readonly_optional_inout.php", line 4, characters 57-61:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_named_readonly_optional_inout.php", line 4, characters 81-85:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_inout.php", line 4, characters 53-57:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_inout_named.php", line 4, characters 58-62:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_inout_named.php", line 4, characters 64-68:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_inout_named_readonly.php", line 4, characters 66-70:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_inout_named_readonly.php", line 4, characters 72-76:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_inout_readonly.php", line 4, characters 61-65:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_inout_readonly_named.php", line 4, characters 66-70:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_inout_readonly_named.php", line 4, characters 81-85:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_named_inout.php", line 4, characters 58-62:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_named_inout.php", line 4, characters 64-68:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_named_inout_readonly.php", line 4, characters 66-70:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_named_inout_readonly.php", line 4, characters 72-76:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_named_readonly_inout.php", line 4, characters 66-70:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_named_readonly_inout.php", line 4, characters 81-85:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_optional.php", line 4, characters 56-63:
Duplicate parameter modifier `optional`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_readonly_inout.php", line 4, characters 70-74:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_readonly_inout_named.php", line 4, characters 75-79:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_readonly_inout_named.php", line 4, characters 81-85:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_readonly_named.php", line 4, characters 70-74:
Invalid parameter modifier order. The correct order is `optional named readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_readonly_named_inout.php", line 4, characters 75-79:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_optional_readonly_named_inout.php", line 4, characters 81-85:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_inout.php", line 4, characters 53-57:
Invalid parameter modifier order. The correct order is `inout readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_inout_named.php", line 4, characters 64-68:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_inout_named_optional.php", line 4, characters 66-70:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_inout_named_optional.php", line 4, characters 72-76:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_inout_optional.php", line 4, characters 61-65:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_inout_optional_named.php", line 4, characters 66-70:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_inout_optional_named.php", line 4, characters 81-85:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_named.php", line 4, characters 53-57:
Invalid parameter modifier order. The correct order is `named readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_named_inout.php", line 4, characters 58-62:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_named_inout_optional.php", line 4, characters 66-70:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_named_inout_optional.php", line 4, characters 72-76:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_named_optional.php", line 4, characters 61-65:
Invalid parameter modifier order. The correct order is `optional named readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_named_optional_inout.php", line 4, characters 66-70:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_named_optional_inout.php", line 4, characters 81-85:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_optional.php", line 4, characters 56-63:
Invalid parameter modifier order. The correct order is `optional readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_optional_inout.php", line 4, characters 70-74:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_optional_inout_named.php", line 4, characters 75-79:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_optional_inout_named.php", line 4, characters 81-85:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_optional_named.php", line 4, characters 61-68:
Invalid parameter modifier order. The correct order is `optional named readonly`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_optional_named_inout.php", line 4, characters 75-79:
A parameter cannot be both `inout` and `named`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_optional_named_inout.php", line 4, characters 81-85:
A parameter cannot be both `optional` and `inout`. (Parsing[1002])
ERROR: File "parameter_modifiers_all_orders_bad.php--function_type_readonly_readonly.php", line 4, characters 56-63:
Duplicate parameter modifier `readonly`. (Parsing[1002])
