Code actions available:
------------------------------------------
Add stubs for missing interface methods (CodeActionKind: "quickfix") SELECTED
Devmate Quick Fix - This interface is not properly implemented (CodeActionKind: "quickfix")
Devmate Agent Fix - This interface is not properly implemented (CodeActionKind: "quickfix")

JSON for selected code action:
------------------------------------------
{
  "title": "Add stubs for missing interface methods",
  "kind": "quickfix",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 11, "character": 0 },
            "end": { "line": 11, "character": 0 }
          },
          "newText": "\n  public function someMethod(): void {}\n"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

interface TheInterface {
  public function someMethod(): void;
}

class C implements TheInterface {
                  // ^ at-caret
  public function bar(): void {
    3 + true;
  }

  public function someMethod(): void {}
}

