Code actions available:
------------------------------------------
Add doc comment (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Add doc comment",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 2, "character": 0 },
            "end": { "line": 2, "character": 0 }
          },
          "newText": "/**\n * \n */\n"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh
// There should be no snippet (`${`...) in the output
/**
 * 
 */
// because we are using `--ide-code-actions-no-experimental-capabilities`

class A/*range-start*//*range-end*/ {}

