ERROR: File "tparam_with_targ_in_new.php", line 13, characters 12-12:
Type arguments are not allowed in this position (Parsing[1002])
ERROR: File "tparam_with_targ_in_new.php", line 14, characters 4-6:
Type arguments are not allowed in this position (Parsing[1002])
ERROR: File "tparam_with_targ_in_new.php", line 9, characters 3-6:
`T` is a type parameter. Type parameters cannot take type arguments (e.g. `T<int>` isn't allowed) (Naming[2047])
ERROR: File "tparam_with_targ_in_new.php", line 10, characters 4-7:
`T` is a type parameter. Type parameters cannot take type arguments (e.g. `T<int>` isn't allowed) (Naming[2047])
ERROR: File "tparam_with_targ_in_new.php", line 11, characters 5-8:
`T` is a type parameter. Type parameters cannot take type arguments (e.g. `T<int>` isn't allowed) (Naming[2047])
