Code actions available:
------------------------------------------
Extract interface (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract interface",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 4, "character": 7 },
            "end": { "line": 4, "character": 7 }
          },
          "newText": "\n  implements Placeholder_"
        },
        {
          "range": {
            "start": { "line": 4, "character": 0 },
            "end": { "line": 4, "character": 0 }
          },
          "newText": "interface Placeholder_ {\n  public function foo(): void;\n}\n\n"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

trait Tr {}

interface Placeholder_ {
  public function foo(): void;
}

class A
  implements Placeholder_ {
  use Tr;
  /*range-start*/
  public function foo(): void {
    400 + 8;
  }
  public int $x;
  /*range-end*/
}

