Code actions available:
------------------------------------------
Extract interface (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract interface",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 4, "character": 25 },
            "end": { "line": 4, "character": 25 }
          },
          "newText": "\n  implements Placeholder_"
        },
        {
          "range": {
            "start": { "line": 4, "character": 0 },
            "end": { "line": 4, "character": 0 }
          },
          "newText": "interface Placeholder_ {\n  public function foo(): void;\n  public function bar(): void;\n}\n\n"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class TheParent {}

interface Placeholder_ {
  public function foo(): void;
  public function bar(): void;
}

class A extends TheParent
  implements Placeholder_ {
  /*range-start*/
  public function foo(): void {
    400 + 8;
  }
  public function bar(): void {
    400 + 8;
  }
  /*range-end*/
}

