Code actions available:
------------------------------------------
Extract interface (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Extract interface",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 2, "character": 7 },
            "end": { "line": 2, "character": 7 }
          },
          "newText": "\n  implements Placeholder_"
        },
        {
          "range": {
            "start": { "line": 2, "character": 0 },
            "end": { "line": 2, "character": 0 }
          },
          "newText": "interface Placeholder_ {\n  public function foo(): Awaitable<void>;\n}\n\n"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

interface Placeholder_ {
  public function foo(): Awaitable<void>;
}

class A
  implements Placeholder_ {
  /*range-start*/
  public async function foo(): Awaitable<void> {}
  /*range-end*/
}

