Code actions available:
------------------------------------------
Add override for TheParent::foo (CodeActionKind: "refactor") SELECTED

JSON for selected code action:
------------------------------------------
{
  "title": "Add override for TheParent::foo",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 7, "character": 55 },
            "end": { "line": 7, "character": 55 }
          },
          "newText": "\n  <<__Override>>\n  public function foo(): void {\n    \n  }\n\n"
        }
      ]
    }
  },
  "command": {
    "title": "Set Cursor Selection",
    "command": "hack.setSelection",
    "arguments": [
      {
        "start": { "line": 10, "character": 4 },
        "end": { "line": 10, "character": 4 }
      },
      {
        "title": "Trigger Inline Suggest",
        "command": "editor.action.inlineSuggest.trigger",
        "arguments": []
      }
    ]
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class TheParent {
  public function foo(): void {}
  private function privFunc(): void {}
}

class B extends /*range-start*/TheParent/*range-end*/ {
  <<__Override>>
  public function foo(): void {
    >||<
  }

}

