(rule
 (target files_to_ignore.fb.ml)
 (action
  (copy# facebook/files_to_ignore.ml files_to_ignore.fb.ml)))

(library
 (name ignore)
 (wrapped false)
 (libraries
  core_kernel
  hh_json
  str
  string
  base
  core
  yojson
  (select
   files_to_ignore.ml
   from
   (facebook -> files_to_ignore.fb.ml)
   (-> files_to_ignore.stubs.ml))))
