{
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "final class MyClass {\n", "  // This is a comment\n",
        "  const int METADATA_ID = 219481;\n", "}"
      ],
      "outputs": [],
      "execution_count": null,
      "metadata": {
        "customInput": "foo_plugin",
        "extensionName": "FOO_EXTENSION",
        "isAgentGenerated": false,
        "language": "hack",
        "originalKey": "32948q24",
        "outputsInitialized": false
      }
    }
  ],
  "metadata": {
    "kernelspec": {
      "name": "bento_kernel_hack",
      "display_name": "hack",
      "language": "hack",
      "metadata": {
        "kernel_name": "bento_kernel_hack",
        "nightly_builds": true,
        "fbpkg_supported": true,
        "cinder_runtime": false,
        "is_prebuilt": true,
        "default_tagged_version": "2093",
        "kernel_version": "2093",
        "download_status": "downloaded"
      }
    },
    "orig_nbformat": 4
  },
  "nbformat": 4
}
