{
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "$m = new MyClass();\n", "echo \"hi1\";\n", "class MyClass {\n",
        "  public function hello(): void {\n", "    echo \"hello\";\n",
        "  }\n", "}\n", "async function notebook_main(): Awaitable<void> {"
      ],
      "outputs": [],
      "execution_count": null,
      "metadata": {
        "output": { "id": 1247934846418027, "loadingStatus": "loaded" },
        "collapsed": true
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "/*@non_hack:\n", "# Check it out\n", "I am a *markdown* **cell**\n",
        "*/"
      ],
      "outputs": [],
      "execution_count": null,
      "metadata": {}
    },
    {
      "cell_type": "code",
      "source": [ "echo \"hi2\";\n", "$m->hello();" ],
      "outputs": [],
      "execution_count": null,
      "metadata": {}
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "hack",
      "language": "hack",
      "name": "bento_kernel_hack"
    },
    "orig_nbformat": 4
  },
  "nbformat": 4
}
Warning: found bad metadata when converting Hack to a notebook: got start-of-cell metadata before the previous cell ended.
Warning: found bad metadata when converting Hack to a notebook: got start-of-cell metadata before the previous cell ended.
Warning: found bad metadata when converting Hack to a notebook: got start-of-cell metadata before the previous cell ended.
