<?hh
// generated by idl-to-hni.php

/* Used as the base class for all closures
 */
class Closure {

  /* @return array
   */
  public final function __debugInfo(): dict<string, mixed> {
    return dict[];
  }
}
