name: (unused), kind: argument, span: line 18, characters 13-15, is_declaration: false
affects_prod_build: true
definition: None

name: \E#ID, kind: enum_class_label, span: line 18, characters 13-15, is_declaration: false
affects_prod_build: true
definition:
 ID
   kind: class constant
   id: class_const::E::ID
   position: line 9, characters 16-17
   span: line 9, character 16 - line 9, character 17
   modifiers: abstract 


