name: \C::instance_prop, kind: property, span: line 14, characters 17-29, is_declaration: false
affects_prod_build: true
definition:
 instance_prop
   kind: property
   id: property::C::instance_prop
   position: line 7, characters 14-27
   span: line 7, character 14 - line 7, character 31
   modifiers: public 


name: \T::instance_prop, kind: property, span: line 14, characters 17-29, is_declaration: false
affects_prod_build: true
definition: None

