Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
Inline method (CodeActionKind: "refactor") SELECTED
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor")

JSON for selected code action:
------------------------------------------
{
  "title": "Inline method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 9, "character": 5 }
          },
          "newText": ""
        },
        {
          "range": {
            "start": { "line": 13, "character": 12 },
            "end": { "line": 13, "character": 12 }
          },
          "newText": "$param_a = \"hello \".\"world\";\n            $param_b = 2 + 2;\n            $z = $param_a;\n            if ($param_b > 1) {\n              $z = $param_a.$param_b;\n            }\n            $res = $z;\n            "
        },
        {
          "range": {
            "start": { "line": 13, "character": 17 },
            "end": { "line": 13, "character": 88 }
          },
          "newText": "$res"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class A {

    public function main(): void {
        if (true) {
            echo "test\n";
            $param_a = "hello "."world";
            $param_b = 2 + 2;
            $z = $param_a;
            if ($param_b > 1) {
              $z = $param_a.$param_b;
            }
            $res = $z;
            $s = $res;
            echo $s . "\n";
        }
    }
}

