Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
Inline method (CodeActionKind: "refactor") SELECTED
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor")

JSON for selected code action:
------------------------------------------
{
  "title": "Inline method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 6, "character": 5 }
          },
          "newText": ""
        },
        {
          "range": {
            "start": { "line": 9, "character": 8 },
            "end": { "line": 9, "character": 8 }
          },
          "newText": "$param_a = \"hello \";\n        $z = $param_a;\n        $res = $z;\n        "
        },
        {
          "range": {
            "start": { "line": 9, "character": 19 },
            "end": { "line": 9, "character": 73 }
          },
          "newText": "$res"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class A {

    public async function main(): Awaitable<void> {
        echo "test\n";
        $param_a = "hello ";
        $z = $param_a;
        $res = $z;
        $s = await $res;
        echo $s . "\n";
    }
}

