Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
Inline method (CodeActionKind: "refactor") SELECTED
Extract into method (CodeActionKind: "refactor")

JSON for selected code action:
------------------------------------------
{
  "title": "Inline method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 4, "character": 0 },
            "end": { "line": 4, "character": 33 }
          },
          "newText": ""
        },
        {
          "range": {
            "start": { "line": 6, "character": 4 },
            "end": { "line": 6, "character": 4 }
          },
          "newText": ""
        },
        {
          "range": {
            "start": { "line": 6, "character": 0 },
            "end": { "line": 6, "character": 45 }
          },
          "newText": ""
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class Klass {
  // ensure we gracefully handle an empty block, which can have weird positions (Pos.none)

  public function bar(): void {
    
  }
}

