Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
Inline method (CodeActionKind: "refactor") SELECTED
Extract into method (CodeActionKind: "refactor")

JSON for selected code action:
------------------------------------------
{
  "title": "Inline method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 7, "character": 3 }
          },
          "newText": ""
        },
        {
          "range": {
            "start": { "line": 10, "character": 4 },
            "end": { "line": 10, "character": 4 }
          },
          "newText": "$x = 3;\n    $z = $a.$b;\n    echo $z;\n    "
        },
        {
          "range": {
            "start": { "line": 10, "character": 0 },
            "end": { "line": 10, "character": 51 }
          },
          "newText": ""
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class A {

  public function foo(): void {
    // We remove the call when it's to a void function.
    $x = 3;
    $z = $a.$b;
    echo $z;
    
    echo "done";
  }
}

