Code actions available:
------------------------------------------
Extract into variable (CodeActionKind: "refactor")
Inline method (CodeActionKind: "refactor") SELECTED
slog variable (CodeActionKind: "refactor")
Extract into method (CodeActionKind: "refactor")

JSON for selected code action:
------------------------------------------
{
  "title": "Inline method",
  "kind": "refactor",
  "diagnostics": [],
  "edit": {
    "changes": {
      "FILE.php": [
        {
          "range": {
            "start": { "line": 3, "character": 0 },
            "end": { "line": 7, "character": 3 }
          },
          "newText": ""
        },
        {
          "range": {
            "start": { "line": 10, "character": 4 },
            "end": { "line": 10, "character": 4 }
          },
          "newText": "$a = \"a\";\n    $b = \"b\";\n    $x_ = 3;\n    $z = $a.$b;\n    $res = $z;\n    "
        },
        {
          "range": {
            "start": { "line": 10, "character": 9 },
            "end": { "line": 10, "character": 63 }
          },
          "newText": "$res"
        }
      ]
    }
  }
}

Applied edit for code action:
------------------------------------------
<?hh

class A {

  public function foo(): void {
    $x = 2;
    $a = "a";
    $b = "b";
    $x_ = 3;
    $z = $a.$b;
    $res = $z;
    $s = $res;
  }
}

