WARN: File "tany_ambiguous.php", line 13, characters 54-58:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
WARN: File "tany_ambiguous.php", line 16, characters 12-22:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
WARN: File "tany_ambiguous.php", line 16, characters 19-22:
This expression has an unresolved type due to a limitation of the typechecker. It is silently compatible with every type, so it can be passed to or returned from any function without triggering a type error, potentially hiding bugs. Please post in the support group for further guidance. (Warn[12036])
ERROR: File "tany_ambiguous.php", line 43, characters 12-27:
Invalid return type (Typing[4110])
  File "tany_ambiguous.php", line 42, characters 27-29:
  Expected `int`
  File "tany_ambiguous.php", line 22, characters 23-28:
  But got `string`
  File "tany_ambiguous.php", line 15, characters 39-49:
    resulting from expanding the type constant `this::TData`
