<?hh

// This doc comment block generated by idl/sysdoc.php
/**
 * ( excerpt from http://php.net/manual/en/class.directory.php )
 *
 * Instances of Directory are created by calling the dir() function, not
 * by the new operator.
 *
 */
class Directory {
  public string $path;
  public resource $handle;

  public function __construct(string $path): void {
    $this->path = $path;
    /* HH_FIXME[4110] opendir returns mixed (resource|false) */
    $this->handle = opendir($path);
  }

  public function read(): mixed {
    /* HH_FIXME[4110] readdir expects resource */
    return readdir($this->handle);
  }

  public function rewind(): void {
    /* HH_FIXME[4110] rewinddir expects resource */
    rewinddir($this->handle);
  }

  public function close(): void {
    /* HH_FIXME[4110] closedir expects resource */
    closedir($this->handle);
  }
}
